$gwx_XC_104=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_104 || [];
function gz$gwx_XC_104_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_104_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_104_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_104_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([[2,'=='],[[7],[3,'motion_status']],[1,0]])
Z([3,'bg-white nav'])
Z([3,'flex text-center'])
Z([1,true])
Z([3,'height: 45%;padding-bottom:60px;'])
Z([3,'bottom'])
Z([[7],[3,'setTaskDialog']])
Z([3,'1026'])
Z([3,'onCancelSetTask'])
Z([3,'onConfirmSetTask'])
Z([[7],[3,'taskList']])
Z([[7],[3,'taskDefaultIndex']])
Z([3,'选择跑步任务'])
Z([3,'paperName'])
Z(z[3])
Z(z[4])
Z(z[5])
Z([[7],[3,'setLineDialog']])
Z(z[7])
Z([3,'onCancelSetLine'])
Z([3,'onConfirmSetLine'])
Z([[7],[3,'columnsLine']])
Z([[7],[3,'lineDefaultIndex']])
Z([3,'选择跑步路线'])
Z([3,'pointName'])
Z([[7],[3,'lockShow']])
Z([3,'9999'])
Z([3,'unlockClick'])
Z([3,'wrapperLock'])
Z([3,'wrapperLockBackground'])
Z([3,'aspectFill'])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/logo.png'])
Z([3,'width:200rpx;color:#fff;font-size:14px;text-align:center;'])
Z([3,'点击解锁'])
Z([[2,'||'],[[2,'=='],[[7],[3,'runType']],[1,0]],[[2,'=='],[[7],[3,'runType']],[1,2]]])
Z([[7],[3,'circles']])
Z([[7],[3,'enableSatellite']])
Z([3,'myMap'])
Z([[7],[3,'latitude']])
Z([[7],[3,'longitude']])
Z([[7],[3,'markers']])
Z([[7],[3,'polyline']])
Z([1,18])
Z([a,[3,'width:100%;height:'],[[7],[3,'screenHeight']],[3,';']])
Z([3,'position:absolute;top:8%;left:50%;transform:translate(-50%,0);width:90%;'])
Z([3,'user-pill-glass flex align-center'])
Z([3,'width:70%;margin-left:30rpx;'])
Z([3,'text-bold text-black margin-left-xs'])
Z([3,'font-size:24rpx;'])
Z([a,[[6],[[7],[3,'userInfo']],[3,'studentName']]])
Z([3,'text-gray margin-left-xs'])
Z(z[48])
Z([a,[[6],[[7],[3,'userInfo']],[3,'schoolCampusName']]])
Z([3,'text-gray margin-left-sm din-font'])
Z(z[48])
Z([a,[[6],[[7],[3,'userInfo']],[3,'snCode']]])
Z([a,[3,'location-signal '],[[7],[3,'locationSignalStatus']]])
Z([a,[[2,'?:'],[[2,'==='],[[7],[3,'locationSignalStatus']],[1,'good']],[1,'🟢'],[[2,'?:'],[[2,'==='],[[7],[3,'locationSignalStatus']],[1,'weak']],[1,'🟡'],[1,'🔴']]]])
Z([[2,'==='],[[7],[3,'locationSignalStatus']],[1,'lost']])
Z([3,'manualRetryLocation'])
Z([3,'signal-tip'])
Z([3,'信号丢失'])
Z([3,'cu-card article '])
Z([3,'cu-item shadow no-card'])
Z([3,'border-radius:20px;'])
Z([3,'flex justify-center align-center'])
Z([3,'height:70rpx;'])
Z([3,'tabSelect'])
Z([a,[[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,0]],[1,'tabselectleftBox '],[1,'notabselectleftBox']],[3,' text-center setRoundBoxcomm ']])
Z([3,'0'])
Z([3,'阳光跑'])
Z(z[67])
Z([a,[[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,2]],[1,'tabselectrightBox '],[1,'notabselectrightBox']],[3,' text-center setRoundBoxcomm']])
Z([3,'2'])
Z([3,'自由跑'])
Z([3,'flex padding-left padding-right justify-center'])
Z([3,'height:120rpx;'])
Z([a,[[2,'?:'],[[2,'!=='],[[7],[3,'motion_status']],[1,0]],[1,'text-blue '],[1,'']],[3,' cu-bar flex text-bold']])
Z([3,'font-size:70rpx;'])
Z([a,[[7],[3,'time_data']]])
Z(z[75])
Z([3,'flex-sub'])
Z([3,'text-center'])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/run/里程icon.png'])
Z([3,'width:70rpx;height:60rpx;'])
Z([3,'text-xs'])
Z([3,'里程KM'])
Z([3,'flex justify-center align-end '])
Z([3,'margin-top:8px;font-size:22px;'])
Z([3,'text-bold'])
Z([a,[[7],[3,'allKm']],[3,'/'],[[6],[[7],[3,'sunrunlimiting']],[3,'mileage']]])
Z(z[81])
Z(z[82])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/run/配速icon.png'])
Z(z[84])
Z(z[85])
Z([3,'配速'])
Z([3,'flex justify-center text-bold '])
Z(z[88])
Z([a,[[7],[3,'speed_data']]])
Z([3,'flex-sub '])
Z(z[82])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/run/拟合icn.png'])
Z(z[84])
Z(z[85])
Z([3,'拟合度'])
Z(z[87])
Z(z[88])
Z(z[89])
Z([a,[[7],[3,'fitDegree']]])
Z([3,'flex align-center '])
Z([3,'margin-top:14px;'])
Z([[2,'!='],[[7],[3,'abnormalPointType']],[1,0]])
Z(z[81])
Z([3,'text-align:center;'])
Z([3,'font-size:20px;font-weight:500;color:red;'])
Z([3,'疑似作弊'])
Z([3,'toggleFold'])
Z([3,' align-center'])
Z([3,'font-size:12px;margin-top:10px;padding:0 24px;'])
Z([3,'display:flex;align-items:center;justify-content:space-between;'])
Z([3,'display:flex;align-items:center;'])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/run/renwumubiao.jpeg'])
Z([3,'width:60rpx;height:70rpx;'])
Z([3,'font-size:14px;font-weight:700;margin-left:12px;overflow:hidden;'])
Z([a,[[6],[[7],[3,'sunrunlimiting']],[3,'paperName']],[3,' - '],z[90][3],[3,'KM']])
Z([[7],[3,'isFold']])
Z([3,'arrow-up'])
Z([[2,'!'],[[7],[3,'isFold']]])
Z([3,'arrow-down'])
Z(z[126])
Z([3,'margin-bottom:8px;'])
Z([3,'display:flex;'])
Z([3,'line-height:20px;margin-right:8px;'])
Z([3,'公里数：'])
Z([3,'配速：'])
Z([3,'时长：'])
Z([3,'拟合度：'])
Z([3,'跑步时间：'])
Z([3,'生效时间：'])
Z([3,'line-height:20px;'])
Z([a,z[90][3],z[125][4]])
Z(z[140])
Z([a,[[7],[3,'fastPaceFormat']],z[125][2],[[7],[3,'slowPaceFormat']]])
Z(z[140])
Z([a,[[6],[[7],[3,'sunrunlimiting']],[3,'minTime']],[3,'分钟 - '],[[6],[[7],[3,'sunrunlimiting']],[3,'maxTime']],[3,'分钟 （配速达标即可）']])
Z(z[140])
Z([a,[[6],[[7],[3,'sunrunlimiting']],[3,'fitDegree']]])
Z(z[140])
Z([a,[[6],[[7],[3,'sunrunlimiting']],[3,'startTime']],[3,' ~ '],[[6],[[7],[3,'sunrunlimiting']],[3,'endTime']]])
Z(z[140])
Z([a,[[6],[[7],[3,'sunrunlimiting']],[3,'startDate']],z[149][2],[[6],[[7],[3,'sunrunlimiting']],[3,'endDate']]])
Z([3,'position:absolute;right:20rpx;bottom:140px;z-index:1025;'])
Z([[2,'=='],[[7],[3,'runType']],[1,0]])
Z([3,'setLineDialogShow'])
Z([a,[[2,'?:'],[[2,'!'],[[7],[3,'setLineBindtap']]],[1,'setLineBoxbg'],[1,'setLineBoxbg2']],[3,' setRoundBoxbtn  ']])
Z([3,'toggleSatellite'])
Z([a,[[2,'?:'],[[2,'!'],[[7],[3,'setSatelliteBindtap']]],[1,'setSatelliteBoxbg'],[1,'setSatelliteBoxbg2']],z[155][2]])
Z([3,'lockClick'])
Z([a,[[2,'?:'],[[2,'!'],[[7],[3,'setLockBindtap']]],[1,'setlockBoxbg'],[1,'setlockBoxbg2']],[3,' setRoundBoxbtn']])
Z([3,'position:fixed;width:100%;bottom:60px;z-index:1024;'])
Z([3,'flex justify-center'])
Z(z[0])
Z([3,'startRun'])
Z([a,[3,'bottoncommBox animation-'],[[7],[3,'animation']],[3,' startRunBox margin-left margin-right round lg shadow']])
Z([3,''])
Z([3,'margin-top'])
Z([3,'https://cppu.xtotoro.com/longmao/sunrunwx/run/runbtnicon.png'])
Z([3,'width:60rpx;height:60rpx;'])
Z([3,'开始跑步'])
Z([[2,'=='],[[7],[3,'motion_status']],[1,1]])
Z([3,'pauseRun'])
Z([a,z[164][1],z[164][2],[3,'  margin-left pauseRunBox margin-right round lg shadow']])
Z([3,'height:180rpx;padding:0 30rpx;'])
Z(z[166])
Z([3,'pause'])
Z([3,'font-size:60rpx;'])
Z([3,'暂停跑步'])
Z([[2,'=='],[[7],[3,'motion_status']],[1,2]])
Z([3,'reRun'])
Z([a,z[164][1],z[164][2],[3,'  margin-left startRunBox margin-right round lg shadow']])
Z(z[173])
Z(z[166])
Z([3,'play'])
Z(z[176])
Z([3,'恢复跑步'])
Z([[2,'||'],[[2,'=='],[[7],[3,'motion_status']],[1,1]],[[2,'=='],[[7],[3,'motion_status']],[1,2]]])
Z([3,'container'])
Z([3,'button-wrapper'])
Z([3,'progress-ring'])
Z([a,[3,'width:'],[[7],[3,'ringSize']],[3,'rpx;height:'],[[7],[3,'ringSize']],[3,'rpx;']])
Z([3,'progress-bar'])
Z([a,[3,'transform:rotate('],[[7],[3,'progressRotation']],[3,'deg);']])
Z([3,'onTouchEnd'])
Z([3,'onTouchStart'])
Z([3,'button overBox shadow'])
Z([3,' padding-top'])
Z([3,'stop'])
Z(z[176])
Z([3,'长按结束'])
Z([[2,'=='],[[7],[3,'runType']],[1,1]])
Z([3,'cu-card article'])
Z([3,'cu-item shadow'])
Z(z[75])
Z(z[82])
Z([3,'cu-bar bg-white'])
Z([3,'action'])
Z([3,'cuIcon-title text-blue'])
Z([3,'运动时间'])
Z([3,'flex margin-left text-xxl text-bold'])
Z([a,z[79][1]])
Z([3,'flex padding-left padding-right'])
Z(z[81])
Z([3,'cu-bar '])
Z(z[206])
Z([3,'cuIcon-title text-red'])
Z([3,'卡路里'])
Z([3,'flex margin-left text-xl text-bold'])
Z([a,[[7],[3,'kcal_data']],[3,' Kcal']])
Z(z[81])
Z(z[213])
Z(z[206])
Z([3,'cuIcon-title text-orange'])
Z(z[96])
Z(z[217])
Z([a,z[99][1]])
Z(z[81])
Z(z[213])
Z(z[206])
Z([3,'cuIcon-title text-green'])
Z([3,'里程'])
Z(z[217])
Z([a,z[90][1],[3,' Km']])
Z([3,'position:fixed;width:100%;bottom:60px;z-index:10001;'])
Z(z[161])
Z(z[0])
Z(z[163])
Z([3,'cu-btn bg-green margin-left margin-right round lg'])
Z([3,'height:200rpx;height:180rpx;padding:0 30rpx;'])
Z(z[169])
Z(z[170])
Z(z[171])
Z([3,'cu-btn bg-blue margin-left margin-right round lg'])
Z(z[173])
Z(z[177])
Z(z[178])
Z(z[179])
Z([3,'cu-btn bg-orange margin-left margin-right round lg'])
Z(z[173])
Z(z[185])
Z(z[186])
Z([3,'stopRun'])
Z([3,'cu-btn bg-red margin-left margin-right round lg'])
Z(z[173])
Z([3,'长按停止'])
Z(z[75])
Z(z[81])
Z(z[81])
Z([3,'../../icon/runer.svg'])
Z([3,'height:1500%'])
Z(z[81])
Z([[7],[3,'showFaceCamera']])
Z([3,'10000'])
Z([3,'face-camera-wrapper'])
Z([3,'face-camera-box'])
Z([3,'face-camera-title'])
Z([3,'cuIcon-scan margin-right-xs'])
Z([a,[[7],[3,'faceCameraTitle']]])
Z([3,'camera-container'])
Z([[2,'!'],[[7],[3,'isCameraReady']]])
Z([3,'camera-placeholder'])
Z([[7],[3,'cameraInitFailed']])
Z([3,'#ff3b30'])
Z([3,'warning-o'])
Z([3,'36px'])
Z([3,'text-gray text-sm margin-top-sm'])
Z(z[114])
Z([3,'相机被占用'])
Z([3,'请结束通话等操作后重试'])
Z([3,'#007aff'])
Z([3,'24px'])
Z([3,'spinner'])
Z(z[275])
Z([3,'相机启动中...'])
Z([[2,'&&'],[[7],[3,'showFaceCamera']],[[7],[3,'isCameraReady']]])
Z([3,'cameraError'])
Z([3,'camera-view'])
Z([3,'front'])
Z([3,'off'])
Z([3,'camera-mask'])
Z([3,'oval-cutout'])
Z([3,'scan-line'])
Z([[2,'&&'],[[2,'==='],[[7],[3,'faceCameraType']],[1,1]],[[2,'>'],[[7],[3,'faceCameraCountdown']],[1,0]]])
Z([3,'face-camera-tips'])
Z([3,'剩余时间：'])
Z([3,'color:#ff3b30;font-weight:bold;font-size:36rpx;'])
Z([a,[[7],[3,'faceCameraCountdown']],[3,'s']])
Z(z[293])
Z([3,'请将面部及双肩对准虚线框内'])
Z([3,'face-camera-actions flex justify-between'])
Z([3,'width:100%;padding:0 40rpx;'])
Z([3,'cancelFaceCamera'])
Z([3,'cu-btn bg-gray round shadow'])
Z([3,'width:45%;height:80rpx;'])
Z([3,'取 消'])
Z(z[271])
Z([3,'retryInitCamera'])
Z([3,'cu-btn bg-orange round shadow'])
Z(z[303])
Z([3,'重新打开'])
Z([3,'takeFacePhoto'])
Z([3,'cu-btn bg-blue round shadow'])
Z(z[303])
Z([3,'拍照打卡'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_104_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_104_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_104=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_104=true;
var x=['./pages/run/index.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_104_1()
var o2XC=_v()
_(r,o2XC)
if(_oz(z,0,e,s,gg)){o2XC.wxVkey=1
var h5XC=_mz(z,'scroll-view',['scrollX',-1,'class',1],[],e,s,gg)
var o6XC=_n('view')
_rz(z,o6XC,'class',2,e,s,gg)
_(h5XC,o6XC)
_(o2XC,h5XC)
}
var c7XC=_mz(z,'van-popup',['round',-1,'closabled',3,'customStyle',1,'position',2,'show',3,'zIndex',4],[],e,s,gg)
var o8XC=_n('view')
var l9XC=_mz(z,'van-picker',['showToolbar',-1,'bind:cancel',8,'bind:confirm',1,'columns',2,'defaultIndex',3,'title',4,'valueKey',5],[],e,s,gg)
_(o8XC,l9XC)
_(c7XC,o8XC)
_(r,c7XC)
var a0XC=_mz(z,'van-popup',['round',-1,'closabled',14,'customStyle',1,'position',2,'show',3,'zIndex',4],[],e,s,gg)
var tAYC=_n('view')
var eBYC=_mz(z,'van-picker',['showToolbar',-1,'bind:cancel',19,'bind:confirm',1,'columns',2,'defaultIndex',3,'title',4,'valueKey',5],[],e,s,gg)
_(tAYC,eBYC)
_(a0XC,tAYC)
_(r,a0XC)
var bCYC=_mz(z,'van-overlay',['show',25,'zIndex',1],[],e,s,gg)
var oDYC=_mz(z,'view',['catch:tap',27,'class',1],[],e,s,gg)
var xEYC=_mz(z,'image',['class',29,'mode',1,'src',2],[],e,s,gg)
_(oDYC,xEYC)
var oFYC=_n('view')
_rz(z,oFYC,'style',32,e,s,gg)
var fGYC=_oz(z,33,e,s,gg)
_(oFYC,fGYC)
_(oDYC,oFYC)
_(bCYC,oDYC)
_(r,bCYC)
var f3XC=_v()
_(r,f3XC)
if(_oz(z,34,e,s,gg)){f3XC.wxVkey=1
var cHYC=_mz(z,'map',['showLocation',-1,'circles',35,'enableSatellite',1,'id',2,'latitude',3,'longitude',4,'markers',5,'polyline',6,'scale',7,'style',8],[],e,s,gg)
var hIYC=_n('view')
_rz(z,hIYC,'style',44,e,s,gg)
var oJYC=_mz(z,'view',['class',45,'style',1],[],e,s,gg)
var cKYC=_mz(z,'view',['class',47,'style',1],[],e,s,gg)
var oLYC=_oz(z,49,e,s,gg)
_(cKYC,oLYC)
_(oJYC,cKYC)
var lMYC=_mz(z,'view',['class',50,'style',1],[],e,s,gg)
var aNYC=_oz(z,52,e,s,gg)
_(lMYC,aNYC)
_(oJYC,lMYC)
var tOYC=_mz(z,'view',['class',53,'style',1],[],e,s,gg)
var ePYC=_oz(z,55,e,s,gg)
_(tOYC,ePYC)
_(oJYC,tOYC)
var bQYC=_n('view')
_rz(z,bQYC,'class',56,e,s,gg)
var xSYC=_n('text')
var oTYC=_oz(z,57,e,s,gg)
_(xSYC,oTYC)
_(bQYC,xSYC)
var oRYC=_v()
_(bQYC,oRYC)
if(_oz(z,58,e,s,gg)){oRYC.wxVkey=1
var fUYC=_mz(z,'text',['bindtap',59,'class',1],[],e,s,gg)
var cVYC=_oz(z,61,e,s,gg)
_(fUYC,cVYC)
_(oRYC,fUYC)
}
oRYC.wxXCkey=1
_(oJYC,bQYC)
_(hIYC,oJYC)
var hWYC=_n('view')
_rz(z,hWYC,'class',62,e,s,gg)
var oXYC=_mz(z,'view',['class',63,'style',1],[],e,s,gg)
var cYYC=_mz(z,'view',['class',65,'style',1],[],e,s,gg)
var oZYC=_mz(z,'view',['bindtap',67,'class',1,'data-id',2],[],e,s,gg)
var l1YC=_oz(z,70,e,s,gg)
_(oZYC,l1YC)
_(cYYC,oZYC)
var a2YC=_mz(z,'view',['bindtap',71,'class',1,'data-id',2],[],e,s,gg)
var t3YC=_oz(z,74,e,s,gg)
_(a2YC,t3YC)
_(cYYC,a2YC)
_(oXYC,cYYC)
var e4YC=_mz(z,'view',['class',75,'style',1],[],e,s,gg)
var b5YC=_mz(z,'view',['class',77,'style',1],[],e,s,gg)
var o6YC=_oz(z,79,e,s,gg)
_(b5YC,o6YC)
_(e4YC,b5YC)
_(oXYC,e4YC)
var x7YC=_n('view')
_rz(z,x7YC,'class',80,e,s,gg)
var o8YC=_n('view')
_rz(z,o8YC,'class',81,e,s,gg)
var f9YC=_n('view')
_rz(z,f9YC,'class',82,e,s,gg)
var c0YC=_n('view')
var hAZC=_mz(z,'image',['src',83,'style',1],[],e,s,gg)
_(c0YC,hAZC)
var oBZC=_n('view')
_rz(z,oBZC,'class',85,e,s,gg)
var cCZC=_oz(z,86,e,s,gg)
_(oBZC,cCZC)
_(c0YC,oBZC)
_(f9YC,c0YC)
_(o8YC,f9YC)
var oDZC=_mz(z,'view',['class',87,'style',1],[],e,s,gg)
var lEZC=_n('text')
_rz(z,lEZC,'class',89,e,s,gg)
var aFZC=_oz(z,90,e,s,gg)
_(lEZC,aFZC)
_(oDZC,lEZC)
_(o8YC,oDZC)
_(x7YC,o8YC)
var tGZC=_n('view')
_rz(z,tGZC,'class',91,e,s,gg)
var eHZC=_n('view')
_rz(z,eHZC,'class',92,e,s,gg)
var bIZC=_n('view')
var oJZC=_mz(z,'image',['src',93,'style',1],[],e,s,gg)
_(bIZC,oJZC)
var xKZC=_n('view')
_rz(z,xKZC,'class',95,e,s,gg)
var oLZC=_oz(z,96,e,s,gg)
_(xKZC,oLZC)
_(bIZC,xKZC)
_(eHZC,bIZC)
_(tGZC,eHZC)
var fMZC=_mz(z,'view',['class',97,'style',1],[],e,s,gg)
var cNZC=_oz(z,99,e,s,gg)
_(fMZC,cNZC)
_(tGZC,fMZC)
_(x7YC,tGZC)
var hOZC=_n('view')
_rz(z,hOZC,'class',100,e,s,gg)
var oPZC=_n('view')
_rz(z,oPZC,'class',101,e,s,gg)
var cQZC=_n('view')
var oRZC=_mz(z,'image',['src',102,'style',1],[],e,s,gg)
_(cQZC,oRZC)
var lSZC=_n('view')
_rz(z,lSZC,'class',104,e,s,gg)
var aTZC=_oz(z,105,e,s,gg)
_(lSZC,aTZC)
_(cQZC,lSZC)
_(oPZC,cQZC)
_(hOZC,oPZC)
var tUZC=_mz(z,'view',['class',106,'style',1],[],e,s,gg)
var eVZC=_n('text')
_rz(z,eVZC,'class',108,e,s,gg)
var bWZC=_oz(z,109,e,s,gg)
_(eVZC,bWZC)
_(tUZC,eVZC)
_(hOZC,tUZC)
_(x7YC,hOZC)
_(oXYC,x7YC)
var oXZC=_mz(z,'view',['class',110,'style',1],[],e,s,gg)
var xYZC=_v()
_(oXZC,xYZC)
if(_oz(z,112,e,s,gg)){xYZC.wxVkey=1
var oZZC=_mz(z,'view',['class',113,'style',1],[],e,s,gg)
var f1ZC=_n('view')
_rz(z,f1ZC,'style',115,e,s,gg)
var c2ZC=_oz(z,116,e,s,gg)
_(f1ZC,c2ZC)
_(oZZC,f1ZC)
_(xYZC,oZZC)
}
xYZC.wxXCkey=1
_(oXYC,oXZC)
var h3ZC=_mz(z,'view',['bindtap',117,'class',1,'style',2],[],e,s,gg)
var c5ZC=_n('view')
_rz(z,c5ZC,'style',120,e,s,gg)
var o6ZC=_n('view')
_rz(z,o6ZC,'style',121,e,s,gg)
var l7ZC=_mz(z,'image',['src',122,'style',1],[],e,s,gg)
_(o6ZC,l7ZC)
var a8ZC=_n('view')
_rz(z,a8ZC,'style',124,e,s,gg)
var t9ZC=_oz(z,125,e,s,gg)
_(a8ZC,t9ZC)
_(o6ZC,a8ZC)
_(c5ZC,o6ZC)
var e0ZC=_n('view')
var bA1C=_v()
_(e0ZC,bA1C)
if(_oz(z,126,e,s,gg)){bA1C.wxVkey=1
var xC1C=_n('van-icon')
_rz(z,xC1C,'name',127,e,s,gg)
_(bA1C,xC1C)
}
var oB1C=_v()
_(e0ZC,oB1C)
if(_oz(z,128,e,s,gg)){oB1C.wxVkey=1
var oD1C=_n('van-icon')
_rz(z,oD1C,'name',129,e,s,gg)
_(oB1C,oD1C)
}
bA1C.wxXCkey=1
bA1C.wxXCkey=3
oB1C.wxXCkey=1
oB1C.wxXCkey=3
_(c5ZC,e0ZC)
_(h3ZC,c5ZC)
var o4ZC=_v()
_(h3ZC,o4ZC)
if(_oz(z,130,e,s,gg)){o4ZC.wxVkey=1
var fE1C=_n('view')
var cF1C=_n('view')
_rz(z,cF1C,'style',131,e,s,gg)
_(fE1C,cF1C)
var hG1C=_n('view')
_rz(z,hG1C,'style',132,e,s,gg)
var oH1C=_n('view')
_rz(z,oH1C,'style',133,e,s,gg)
var cI1C=_n('view')
var oJ1C=_oz(z,134,e,s,gg)
_(cI1C,oJ1C)
_(oH1C,cI1C)
var lK1C=_n('view')
var aL1C=_oz(z,135,e,s,gg)
_(lK1C,aL1C)
_(oH1C,lK1C)
var tM1C=_n('view')
var eN1C=_oz(z,136,e,s,gg)
_(tM1C,eN1C)
_(oH1C,tM1C)
var bO1C=_n('view')
var oP1C=_oz(z,137,e,s,gg)
_(bO1C,oP1C)
_(oH1C,bO1C)
var xQ1C=_n('view')
var oR1C=_oz(z,138,e,s,gg)
_(xQ1C,oR1C)
_(oH1C,xQ1C)
var fS1C=_n('view')
var cT1C=_oz(z,139,e,s,gg)
_(fS1C,cT1C)
_(oH1C,fS1C)
_(hG1C,oH1C)
var hU1C=_n('view')
var oV1C=_n('view')
_rz(z,oV1C,'style',140,e,s,gg)
var cW1C=_oz(z,141,e,s,gg)
_(oV1C,cW1C)
_(hU1C,oV1C)
var oX1C=_n('view')
_rz(z,oX1C,'style',142,e,s,gg)
var lY1C=_oz(z,143,e,s,gg)
_(oX1C,lY1C)
_(hU1C,oX1C)
var aZ1C=_n('view')
_rz(z,aZ1C,'style',144,e,s,gg)
var t11C=_oz(z,145,e,s,gg)
_(aZ1C,t11C)
_(hU1C,aZ1C)
var e21C=_n('view')
_rz(z,e21C,'style',146,e,s,gg)
var b31C=_oz(z,147,e,s,gg)
_(e21C,b31C)
_(hU1C,e21C)
var o41C=_n('view')
_rz(z,o41C,'style',148,e,s,gg)
var x51C=_oz(z,149,e,s,gg)
_(o41C,x51C)
_(hU1C,o41C)
var o61C=_n('view')
_rz(z,o61C,'style',150,e,s,gg)
var f71C=_oz(z,151,e,s,gg)
_(o61C,f71C)
_(hU1C,o61C)
_(hG1C,hU1C)
_(fE1C,hG1C)
_(o4ZC,fE1C)
}
o4ZC.wxXCkey=1
_(oXYC,h3ZC)
_(hWYC,oXYC)
_(hIYC,hWYC)
_(cHYC,hIYC)
var c81C=_n('view')
_rz(z,c81C,'style',152,e,s,gg)
var h91C=_v()
_(c81C,h91C)
if(_oz(z,153,e,s,gg)){h91C.wxVkey=1
var o01C=_mz(z,'view',['bindtap',154,'class',1],[],e,s,gg)
_(h91C,o01C)
}
var cA2C=_mz(z,'view',['bindtap',156,'class',1],[],e,s,gg)
_(c81C,cA2C)
var oB2C=_mz(z,'view',['bindtap',158,'class',1],[],e,s,gg)
_(c81C,oB2C)
h91C.wxXCkey=1
_(cHYC,c81C)
var lC2C=_n('view')
_rz(z,lC2C,'style',160,e,s,gg)
var aD2C=_n('view')
_rz(z,aD2C,'class',161,e,s,gg)
var tE2C=_v()
_(aD2C,tE2C)
if(_oz(z,162,e,s,gg)){tE2C.wxVkey=1
var xI2C=_mz(z,'view',['bindtap',163,'class',1],[],e,s,gg)
var oJ2C=_mz(z,'image',['alt',165,'class',1,'src',2,'style',3],[],e,s,gg)
_(xI2C,oJ2C)
var fK2C=_n('view')
var cL2C=_oz(z,169,e,s,gg)
_(fK2C,cL2C)
_(xI2C,fK2C)
_(tE2C,xI2C)
}
var eF2C=_v()
_(aD2C,eF2C)
if(_oz(z,170,e,s,gg)){eF2C.wxVkey=1
var hM2C=_mz(z,'view',['bindtap',171,'class',1,'style',2],[],e,s,gg)
var oN2C=_n('view')
_rz(z,oN2C,'class',174,e,s,gg)
var cO2C=_mz(z,'van-icon',['name',175,'style',1],[],e,s,gg)
_(oN2C,cO2C)
_(hM2C,oN2C)
var oP2C=_n('view')
var lQ2C=_oz(z,177,e,s,gg)
_(oP2C,lQ2C)
_(hM2C,oP2C)
_(eF2C,hM2C)
}
var bG2C=_v()
_(aD2C,bG2C)
if(_oz(z,178,e,s,gg)){bG2C.wxVkey=1
var aR2C=_mz(z,'view',['bindtap',179,'class',1,'style',2],[],e,s,gg)
var tS2C=_n('view')
_rz(z,tS2C,'class',182,e,s,gg)
var eT2C=_mz(z,'van-icon',['name',183,'style',1],[],e,s,gg)
_(tS2C,eT2C)
_(aR2C,tS2C)
var bU2C=_n('view')
var oV2C=_oz(z,185,e,s,gg)
_(bU2C,oV2C)
_(aR2C,bU2C)
_(bG2C,aR2C)
}
var oH2C=_v()
_(aD2C,oH2C)
if(_oz(z,186,e,s,gg)){oH2C.wxVkey=1
var xW2C=_n('view')
_rz(z,xW2C,'class',187,e,s,gg)
var oX2C=_n('view')
_rz(z,oX2C,'class',188,e,s,gg)
var fY2C=_mz(z,'view',['class',189,'style',1],[],e,s,gg)
var cZ2C=_mz(z,'view',['class',191,'style',1],[],e,s,gg)
_(fY2C,cZ2C)
_(oX2C,fY2C)
var h12C=_mz(z,'view',['bindtouchend',193,'bindtouchstart',1,'class',2],[],e,s,gg)
var o22C=_n('view')
_rz(z,o22C,'class',196,e,s,gg)
var c32C=_mz(z,'van-icon',['name',197,'style',1],[],e,s,gg)
_(o22C,c32C)
_(h12C,o22C)
var o42C=_n('view')
var l52C=_n('text')
var a62C=_oz(z,199,e,s,gg)
_(l52C,a62C)
_(o42C,l52C)
_(h12C,o42C)
_(oX2C,h12C)
_(xW2C,oX2C)
_(oH2C,xW2C)
}
tE2C.wxXCkey=1
eF2C.wxXCkey=1
eF2C.wxXCkey=3
bG2C.wxXCkey=1
bG2C.wxXCkey=3
oH2C.wxXCkey=1
oH2C.wxXCkey=3
_(lC2C,aD2C)
_(cHYC,lC2C)
_(f3XC,cHYC)
}
var c4XC=_v()
_(r,c4XC)
if(_oz(z,200,e,s,gg)){c4XC.wxVkey=1
var t72C=_n('view')
var e82C=_n('view')
var b92C=_n('view')
_rz(z,b92C,'class',201,e,s,gg)
var o02C=_n('view')
_rz(z,o02C,'class',202,e,s,gg)
var xA3C=_n('view')
_rz(z,xA3C,'class',203,e,s,gg)
var oB3C=_n('view')
_rz(z,oB3C,'class',204,e,s,gg)
var fC3C=_n('view')
_rz(z,fC3C,'class',205,e,s,gg)
var cD3C=_n('view')
_rz(z,cD3C,'class',206,e,s,gg)
var hE3C=_n('text')
_rz(z,hE3C,'class',207,e,s,gg)
_(cD3C,hE3C)
var oF3C=_oz(z,208,e,s,gg)
_(cD3C,oF3C)
_(fC3C,cD3C)
_(oB3C,fC3C)
var cG3C=_n('view')
_rz(z,cG3C,'class',209,e,s,gg)
var oH3C=_oz(z,210,e,s,gg)
_(cG3C,oH3C)
_(oB3C,cG3C)
_(xA3C,oB3C)
_(o02C,xA3C)
var lI3C=_n('view')
_rz(z,lI3C,'class',211,e,s,gg)
var aJ3C=_n('view')
_rz(z,aJ3C,'class',212,e,s,gg)
var tK3C=_n('view')
_rz(z,tK3C,'class',213,e,s,gg)
var eL3C=_n('view')
_rz(z,eL3C,'class',214,e,s,gg)
var bM3C=_n('text')
_rz(z,bM3C,'class',215,e,s,gg)
_(eL3C,bM3C)
var oN3C=_oz(z,216,e,s,gg)
_(eL3C,oN3C)
_(tK3C,eL3C)
_(aJ3C,tK3C)
var xO3C=_n('view')
_rz(z,xO3C,'class',217,e,s,gg)
var oP3C=_oz(z,218,e,s,gg)
_(xO3C,oP3C)
_(aJ3C,xO3C)
_(lI3C,aJ3C)
var fQ3C=_n('view')
_rz(z,fQ3C,'class',219,e,s,gg)
var cR3C=_n('view')
_rz(z,cR3C,'class',220,e,s,gg)
var hS3C=_n('view')
_rz(z,hS3C,'class',221,e,s,gg)
var oT3C=_n('text')
_rz(z,oT3C,'class',222,e,s,gg)
_(hS3C,oT3C)
var cU3C=_oz(z,223,e,s,gg)
_(hS3C,cU3C)
_(cR3C,hS3C)
_(fQ3C,cR3C)
var oV3C=_n('view')
_rz(z,oV3C,'class',224,e,s,gg)
var lW3C=_oz(z,225,e,s,gg)
_(oV3C,lW3C)
_(fQ3C,oV3C)
_(lI3C,fQ3C)
var aX3C=_n('view')
_rz(z,aX3C,'class',226,e,s,gg)
var tY3C=_n('view')
_rz(z,tY3C,'class',227,e,s,gg)
var eZ3C=_n('view')
_rz(z,eZ3C,'class',228,e,s,gg)
var b13C=_n('text')
_rz(z,b13C,'class',229,e,s,gg)
_(eZ3C,b13C)
var o23C=_oz(z,230,e,s,gg)
_(eZ3C,o23C)
_(tY3C,eZ3C)
_(aX3C,tY3C)
var x33C=_n('view')
_rz(z,x33C,'class',231,e,s,gg)
var o43C=_oz(z,232,e,s,gg)
_(x33C,o43C)
_(aX3C,x33C)
_(lI3C,aX3C)
_(o02C,lI3C)
_(b92C,o02C)
_(e82C,b92C)
_(t72C,e82C)
var f53C=_n('view')
_rz(z,f53C,'style',233,e,s,gg)
var c63C=_n('view')
_rz(z,c63C,'class',234,e,s,gg)
var h73C=_v()
_(c63C,h73C)
if(_oz(z,235,e,s,gg)){h73C.wxVkey=1
var lA4C=_mz(z,'button',['bindtap',236,'class',1,'style',2],[],e,s,gg)
var aB4C=_oz(z,239,e,s,gg)
_(lA4C,aB4C)
_(h73C,lA4C)
}
var o83C=_v()
_(c63C,o83C)
if(_oz(z,240,e,s,gg)){o83C.wxVkey=1
var tC4C=_mz(z,'button',['bindtap',241,'class',1,'style',2],[],e,s,gg)
var eD4C=_oz(z,244,e,s,gg)
_(tC4C,eD4C)
_(o83C,tC4C)
}
var c93C=_v()
_(c63C,c93C)
if(_oz(z,245,e,s,gg)){c93C.wxVkey=1
var bE4C=_mz(z,'button',['bindtap',246,'class',1,'style',2],[],e,s,gg)
var oF4C=_oz(z,249,e,s,gg)
_(bE4C,oF4C)
_(c93C,bE4C)
}
var o03C=_v()
_(c63C,o03C)
if(_oz(z,250,e,s,gg)){o03C.wxVkey=1
var xG4C=_mz(z,'button',['bindlongpress',251,'class',1,'style',2],[],e,s,gg)
var oH4C=_oz(z,254,e,s,gg)
_(xG4C,oH4C)
_(o03C,xG4C)
}
h73C.wxXCkey=1
o83C.wxXCkey=1
c93C.wxXCkey=1
o03C.wxXCkey=1
_(f53C,c63C)
_(t72C,f53C)
var fI4C=_n('view')
_rz(z,fI4C,'class',255,e,s,gg)
var cJ4C=_n('view')
_rz(z,cJ4C,'class',256,e,s,gg)
_(fI4C,cJ4C)
var hK4C=_n('view')
_rz(z,hK4C,'class',257,e,s,gg)
var oL4C=_mz(z,'image',['src',258,'style',1],[],e,s,gg)
_(hK4C,oL4C)
_(fI4C,hK4C)
var cM4C=_n('view')
_rz(z,cM4C,'class',260,e,s,gg)
_(fI4C,cM4C)
_(t72C,fI4C)
_(c4XC,t72C)
}
var oN4C=_mz(z,'van-overlay',['show',261,'zIndex',1],[],e,s,gg)
var lO4C=_n('view')
_rz(z,lO4C,'class',263,e,s,gg)
var aP4C=_n('view')
_rz(z,aP4C,'class',264,e,s,gg)
var eR4C=_n('view')
_rz(z,eR4C,'class',265,e,s,gg)
var bS4C=_n('text')
_rz(z,bS4C,'class',266,e,s,gg)
_(eR4C,bS4C)
var oT4C=_oz(z,267,e,s,gg)
_(eR4C,oT4C)
_(aP4C,eR4C)
var xU4C=_n('view')
_rz(z,xU4C,'class',268,e,s,gg)
var oV4C=_v()
_(xU4C,oV4C)
if(_oz(z,269,e,s,gg)){oV4C.wxVkey=1
var cX4C=_n('view')
_rz(z,cX4C,'class',270,e,s,gg)
var hY4C=_v()
_(cX4C,hY4C)
if(_oz(z,271,e,s,gg)){hY4C.wxVkey=1
var oZ4C=_mz(z,'van-icon',['color',272,'name',1,'size',2],[],e,s,gg)
_(hY4C,oZ4C)
var c14C=_mz(z,'view',['class',275,'style',1],[],e,s,gg)
var o24C=_oz(z,277,e,s,gg)
_(c14C,o24C)
var l34C=_n('br')
_(c14C,l34C)
var a44C=_oz(z,278,e,s,gg)
_(c14C,a44C)
_(hY4C,c14C)
}
else{hY4C.wxVkey=2
var t54C=_mz(z,'van-loading',['color',279,'size',1,'type',2],[],e,s,gg)
_(hY4C,t54C)
var e64C=_n('view')
_rz(z,e64C,'class',282,e,s,gg)
var b74C=_oz(z,283,e,s,gg)
_(e64C,b74C)
_(hY4C,e64C)
}
hY4C.wxXCkey=1
hY4C.wxXCkey=3
hY4C.wxXCkey=3
_(oV4C,cX4C)
}
var fW4C=_v()
_(xU4C,fW4C)
if(_oz(z,284,e,s,gg)){fW4C.wxVkey=1
var o84C=_mz(z,'camera',['binderror',285,'class',1,'devicePosition',2,'flash',3],[],e,s,gg)
var x94C=_n('view')
_rz(z,x94C,'class',289,e,s,gg)
var o04C=_n('view')
_rz(z,o04C,'class',290,e,s,gg)
_(x94C,o04C)
_(o84C,x94C)
var fA5C=_n('view')
_rz(z,fA5C,'class',291,e,s,gg)
_(o84C,fA5C)
_(fW4C,o84C)
}
oV4C.wxXCkey=1
oV4C.wxXCkey=3
fW4C.wxXCkey=1
_(aP4C,xU4C)
var tQ4C=_v()
_(aP4C,tQ4C)
if(_oz(z,292,e,s,gg)){tQ4C.wxVkey=1
var cB5C=_n('view')
_rz(z,cB5C,'class',293,e,s,gg)
var hC5C=_oz(z,294,e,s,gg)
_(cB5C,hC5C)
var oD5C=_n('text')
_rz(z,oD5C,'style',295,e,s,gg)
var cE5C=_oz(z,296,e,s,gg)
_(oD5C,cE5C)
_(cB5C,oD5C)
_(tQ4C,cB5C)
}
else{tQ4C.wxVkey=2
var oF5C=_n('view')
_rz(z,oF5C,'class',297,e,s,gg)
var lG5C=_oz(z,298,e,s,gg)
_(oF5C,lG5C)
_(tQ4C,oF5C)
}
var aH5C=_mz(z,'view',['class',299,'style',1],[],e,s,gg)
var eJ5C=_mz(z,'button',['bindtap',301,'class',1,'style',2],[],e,s,gg)
var bK5C=_oz(z,304,e,s,gg)
_(eJ5C,bK5C)
_(aH5C,eJ5C)
var tI5C=_v()
_(aH5C,tI5C)
if(_oz(z,305,e,s,gg)){tI5C.wxVkey=1
var oL5C=_mz(z,'button',['bindtap',306,'class',1,'style',2],[],e,s,gg)
var xM5C=_oz(z,309,e,s,gg)
_(oL5C,xM5C)
_(tI5C,oL5C)
}
else{tI5C.wxVkey=2
var oN5C=_mz(z,'button',['bindtap',310,'class',1,'style',2],[],e,s,gg)
var fO5C=_oz(z,313,e,s,gg)
_(oN5C,fO5C)
_(tI5C,oN5C)
}
tI5C.wxXCkey=1
_(aP4C,aH5C)
tQ4C.wxXCkey=1
_(lO4C,aP4C)
_(oN4C,lO4C)
_(r,oN4C)
o2XC.wxXCkey=1
f3XC.wxXCkey=1
f3XC.wxXCkey=3
c4XC.wxXCkey=1
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_104";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_104();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/run/index.wxml'] = [$gwx_XC_104, './pages/run/index.wxml'];else __wxAppCode__['pages/run/index.wxml'] = $gwx_XC_104( './pages/run/index.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/run/index.wxss']=setCssToHead([".",[1],"container{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"cu-card\x3e.",[1],"cu-item{background-color:hsla(0,0%,100%,.85);border:1px solid hsla(0,0%,100%,.8);border-radius:",[0,12],";box-shadow:0 8px 12px 0 rgba(31,38,135,.15);position:relative;z-index:1}\n.",[1],"setRoundBox{background-color:#fff;border-radius:50%;box-shadow:0 4px 8px rgba(0,0,0,.2);color:rgba(0,0,0,.582);font-size:12px;margin:",[0,20]," 0;text-align:center;width:",[0,70],"}\n.",[1],"setRoundBox,.",[1],"setRoundBoxcomm{height:",[0,70],";line-height:",[0,70],"}\n.",[1],"setRoundBoxcomm{color:#fff;width:50%}\n.",[1],"padding.",[1],"align-center wx-view[wx-if]{-webkit-animation:fadeIn .3s ease;animation:fadeIn .3s ease}\n@-webkit-keyframes fadeIn{from{opacity:0;-webkit-transform:translateY(",[0,-10],");transform:translateY(",[0,-10],")}\nto{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes fadeIn{from{opacity:0;-webkit-transform:translateY(",[0,-10],");transform:translateY(",[0,-10],")}\nto{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"tabselectleftBox{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/Selected-left.png\x22);background-size:100% 100%;width:55%}\n.",[1],"notabselectleftBox{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/Unselected-left.png\x22);background-size:100% 100%;color:#b1c4da;width:45%}\n.",[1],"tabselectrightBox{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/Selected-right.png\x22);background-size:100% 100%;width:55%}\n.",[1],"notabselectrightBox{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/Unselected-right.png\x22);background-size:100% 100%;color:#b1c4da;width:45%}\n.",[1],"setRoundBoxbtn{font-size:12px;height:",[0,90],";margin:",[0,30]," 0;width:",[0,90],"}\n.",[1],"setLineBoxbg{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/路线.png\x22);background-size:100% 100%}\n.",[1],"setSatelliteBoxbg{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/卫星地图.png\x22);background-size:100% 100%}\n.",[1],"setlockBoxbg{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/锁屏.png\x22);background-size:100% 100%}\n.",[1],"setLineBoxbg2{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/路线点击.png\x22);background-size:100% 100%}\n.",[1],"setSatelliteBoxbg2{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/卫星地图点击.png\x22);background-size:100% 100%}\n.",[1],"setlockBoxbg2{background-image:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/run/锁屏点击.png\x22);background-size:100% 100%}\n.",[1],"wrapperLock{border-radius:",[0,10],";height:",[0,120],";left:50%;position:absolute;text-align:center;top:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);width:",[0,200],"}\n.",[1],"wrapperLockBackground{height:100%;height:",[0,120],";width:100%;width:",[0,120],"}\n.",[1],"button-wrapper{display:inline-block;position:relative}\n.",[1],"startRunBox{background-image:-moz-linear-gradient(90deg,#29f19c 0,#02a1f9 100%);background-image:-webkit-linear-gradient(90deg,#29f19c,#02a1f9);background-image:-ms-linear-gradient(90deg,#29f19c 0,#02a1f9 100%)}\n.",[1],"pauseRunBox,.",[1],"startRunBox{background-color:hsla(0,0%,100%,0);color:#fff;font-size:13px}\n.",[1],"pauseRunBox{background-image:-moz-linear-gradient(90deg,#276cfa 35%,#a4e5ff 100%);background-image:-webkit-linear-gradient(90deg,#276cfa 35%,#a4e5ff);background-image:-ms-linear-gradient(90deg,#276cfa 35%,#a4e5ff 100%);border-radius:50%}\n.",[1],"reRunBox{background-color:hsla(0,0%,100%,0)}\n.",[1],"overBox,.",[1],"reRunBox{color:#fff;font-size:13px}\n.",[1],"overBox{background-image:-moz-linear-gradient(90deg,#c13e35 35%,#e2af5e 100%);background-image:-webkit-linear-gradient(90deg,#c13e35 35%,#e2af5e);background-image:-ms-linear-gradient(90deg,#c13e35 35%,#e2af5e 100%);border-radius:50%}\n.",[1],"bottoncommBox{background-color:#fff}\n.",[1],"bottoncommBox,.",[1],"button{border-radius:50%;color:#fff;height:",[0,180],";text-align:center;width:",[0,182],"}\n.",[1],"button{position:relative;transition:-webkit-transform .1s ease;transition:transform .1s ease;transition:transform .1s ease,-webkit-transform .1s ease}\n.",[1],"button:active{-webkit-transform:scale(.81);transform:scale(.81)}\n.",[1],"progress-ring{border:4px solid rgba(0,0,0,.2);border-radius:50%}\n.",[1],"progress-bar,.",[1],"progress-ring{left:0;position:absolute;top:0}\n.",[1],"progress-bar{border:4px solid #f60;border-radius:50%;border-top-color:transparent;height:100%;transition:-webkit-transform .1s ease;transition:transform .1s ease;transition:transform .1s ease,-webkit-transform .1s ease;width:100%}\n.",[1],"face-camera-wrapper{height:100vh;-webkit-justify-content:center;justify-content:center}\n.",[1],"face-camera-box,.",[1],"face-camera-wrapper{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"face-camera-box{background:hsla(0,0%,100%,.95);border-radius:",[0,40],";box-shadow:0 ",[0,16]," ",[0,48]," rgba(0,0,0,.2);-webkit-flex-direction:column;flex-direction:column;padding:",[0,50]," ",[0,40],";width:85%}\n.",[1],"face-camera-title{color:#1c1c1e;font-size:",[0,36],";font-weight:700;letter-spacing:",[0,2],";margin-bottom:",[0,30],"}\n.",[1],"camera-container{background-color:#f2f2f7;border:",[0,4]," solid rgba(0,122,255,.3);border-radius:",[0,24],";box-shadow:inset 0 0 ",[0,20]," rgba(0,122,255,.1);height:",[0,520],";margin-bottom:",[0,30],";overflow:hidden;position:relative;width:",[0,400],"}\n.",[1],"camera-placeholder{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:100%;-webkit-justify-content:center;justify-content:center;width:100%}\n.",[1],"camera-view{height:100%;position:relative;width:100%}\n.",[1],"camera-mask{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;height:100%;-webkit-justify-content:center;justify-content:center;left:0;overflow:hidden;position:absolute;top:0;width:100%;z-index:10}\n.",[1],"oval-cutout{border:",[0,6]," dashed hsla(0,0%,100%,.8);border-radius:50% 50% 40% 40%/40% 40% 60% 60%;box-shadow:0 0 0 ",[0,1000]," rgba(0,0,0,.45);height:",[0,340],";width:",[0,260],"}\n.",[1],"scan-line{-webkit-animation:scan 3.5s linear infinite;animation:scan 3.5s linear infinite;background-color:#007aff;box-shadow:0 0 ",[0,16]," #007aff;height:",[0,4],";left:0;position:absolute;top:0;width:100%;z-index:20}\n@-webkit-keyframes scan{0%{-webkit-transform:translateY(0);transform:translateY(0)}\n50%{-webkit-transform:translateY(",[0,520],");transform:translateY(",[0,520],")}\n100%{-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes scan{0%{-webkit-transform:translateY(0);transform:translateY(0)}\n50%{-webkit-transform:translateY(",[0,520],");transform:translateY(",[0,520],")}\n100%{-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"face-camera-tips{color:#8e8e93;font-size:",[0,26],";margin-bottom:",[0,40],";text-align:center}\n.",[1],"face-camera-actions{display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;width:100%}\n.",[1],"user-pill-glass{background:hsla(0,0%,100%,.7);background-color:hsla(0,0%,100%,.85);border:",[0,1]," solid hsla(0,0%,100%,.4);border-radius:",[0,32],";box-sizing:border-box;height:100%;padding:",[0,6]," ",[0,0]," ",[0,6]," ",[0,10],"}\n.",[1],"border-top-white-light{background-color:hsla(0,0%,100%,.2);height:1px;width:100%}\n.",[1],"bg-white-transparent{background-color:hsla(0,0%,100%,.15)}\n.",[1],"border-top-dashed{border-top:1px dashed hsla(0,0%,100%,.3)}\n.",[1],"text-xxl{font-size:",[0,44],"}\n.",[1],"text-md{font-size:",[0,28],"}\n.",[1],"location-signal{border-radius:",[0,40],";color:#fff;font-size:",[0,24],";padding:",[0,10]," ",[0,20],";z-index:10}\n.",[1],"signal-tip{color:#ff6b6b;margin-left:",[0,10],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/run/index.wxss:1:622)",{path:"./pages/run/index.wxss"});
}