$gwx_XC_105=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_105 || [];
function gz$gwx_XC_105_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_105_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_105_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_105_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'background-blobs'])
Z([3,'blob blob-1'])
Z([3,'blob blob-2'])
Z([3,'main-container fade-in'])
Z([3,'glass-notice margin-bottom'])
Z([[2,'?:'],[[2,'!'],[[7],[3,'isCloud']]],[1,'background: rgba(255, 149, 0, 0.1); border-color: rgba(255, 149, 0, 0.2);'],[1,'']])
Z([3,'notice-text'])
Z([[2,'?:'],[[2,'!'],[[7],[3,'isCloud']]],[1,'color: #ff9500;'],[1,'']])
Z([a,[[2,'?:'],[[7],[3,'isCloud']],[1,'成绩计算中，约0-5分钟后请至云端查看。'],[1,'⚠️ 网络堵塞，成绩已安全存放在本地手机中。']]])
Z([3,'glass-card padding-lg margin-bottom text-center relative'])
Z([3,'flex justify-between align-center margin-bottom-sm'])
Z([3,'user-pill-glass flex align-center'])
Z([3,'text-bold text-black margin-left-xs'])
Z([3,'font-size:28rpx;'])
Z([a,[[6],[[7],[3,'userInfo']],[3,'studentName']]])
Z([3,'text-gray margin-left-xs'])
Z([3,'font-size:24rpx;'])
Z([a,[[6],[[7],[3,'userInfo']],[3,'schoolCampusName']]])
Z([3,'text-gray margin-left-sm din-font'])
Z(z[16])
Z([a,[[6],[[7],[3,'userInfo']],[3,'snCode']]])
Z([3,'capsule-tag'])
Z([a,[[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,0]],[1,'text-orange'],[1,'text-green']],[3,' text-bold']])
Z([a,[[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,0]],[1,'阳光跑'],[1,'自由跑']]])
Z([3,'margin-tb-lg'])
Z([3,'flex align-baseline justify-center'])
Z([3,'hero-number din-font'])
Z([a,[[7],[3,'distance_data']]])
Z([3,'text-xl text-gray margin-left-sm'])
Z([3,'font-weight:400;'])
Z([3,'km'])
Z([3,'grid-stats'])
Z([3,'stat-item'])
Z([3,'stat-val din-font'])
Z([a,[[7],[3,'time_data']]])
Z([3,'stat-label'])
Z([3,'时长'])
Z([3,'stat-item border-left border-right'])
Z(z[33])
Z([a,[[7],[3,'speed_data']]])
Z(z[35])
Z([3,'配速'])
Z(z[32])
Z(z[33])
Z([a,[[7],[3,'kcal_data']]])
Z(z[35])
Z([3,'千卡'])
Z([3,'margin-top pt-sm border-top flex justify-center align-center'])
Z([3,'text-xs text-gray'])
Z([3,'轨迹拟合度'])
Z([3,'text-sm text-black margin-left-xs text-bold din-font'])
Z([a,[[7],[3,'fitDegree']]])
Z([[7],[3,'isCloud']])
Z([a,[3,'glass-card status-card '],[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'sunRunStatus']],[1,0]],[1,'bg-gradient-red'],[1,'bg-gradient-blue']],[3,' margin-bottom shadow-blur padding-lg']])
Z([3,'flex flex-direction align-center justify-center margin-bottom'])
Z([3,'flex align-center justify-center'])
Z([3,'letter-spacing:2rpx;'])
Z([3,'text-xxl text-bold text-white'])
Z([a,[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'sunRunStatus']],[1,0]],[1,'成绩无效'],[1,'成绩有效']]])
Z([[2,'=='],[[6],[[7],[3,'runPointData']],[3,'sunRunStatus']],[1,0]])
Z([3,'goappeal'])
Z([3,'appeal-glass-btn margin-left-sm pulse-effect'])
Z([3,'去申诉'])
Z([3,'cuIcon-right margin-left-xs'])
Z(z[16])
Z([[6],[[7],[3,'runPointData']],[3,'sunRunMsg']])
Z([3,'text-white margin-top-sm text-sm text-center'])
Z([3,'opacity:0.85;line-height:1.4;'])
Z([a,[[6],[[7],[3,'runPointData']],[3,'sunRunMsg']]])
Z([[2,'&&'],[[6],[[7],[3,'runPointData']],[3,'sunRunMsg']],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'sunRunMsg']],[1,'点位不达标']]])
Z(z[66])
Z(z[67])
Z([3,'若多次出现点位不达标，或频繁触发手机打卡，请前往-\x3e跑步制证菜单，重新制证'])
Z([3,'border-top-white-light margin-bottom'])
Z([[2,'=='],[[6],[[7],[3,'sunrunConfig']],[3,'sunrunPointShowOff']],[1,'1']])
Z([3,'flex text-center text-white margin-bottom-sm'])
Z([3,'opacity:0.95;'])
Z([3,'flex-sub'])
Z([3,'text-xl text-bold din-font'])
Z([a,[[6],[[7],[3,'runPointData']],[3,'allCount']]])
Z([3,'text-xs margin-top-xs'])
Z([3,'opacity:0.8;'])
Z([3,'应过点'])
Z(z[77])
Z(z[78])
Z([a,[[6],[[7],[3,'runPointData']],[3,'nullCount']]])
Z(z[80])
Z(z[81])
Z([3,'未过点'])
Z(z[77])
Z(z[78])
Z([a,[[6],[[7],[3,'runPointData']],[3,'alreadyCount']]])
Z(z[80])
Z(z[81])
Z([3,'已过点'])
Z([3,'bg-white-transparent radius padding-sm margin-top-sm'])
Z([3,'flex justify-between align-center'])
Z([3,'text-md text-bold text-white flex align-center'])
Z([3,'cuIcon-info margin-right-xs'])
Z([[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,0]])
Z([3,'需补卡'])
Z([[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,1]])
Z([3,'无需补卡'])
Z([3,'已补卡'])
Z([3,'text-white text-sm text-right'])
Z([3,'opacity:0.9;'])
Z(z[99])
Z([[2,'=='],[[6],[[7],[3,'reissueCardData']],[3,'bkStatus']],[1,1]])
Z([3,'剩余次数:'])
Z([3,'text-bold text-lg'])
Z([a,[[6],[[7],[3,'reissueCardData']],[3,'count']]])
Z([3,'请前往补卡机操作'])
Z([3,'前往云端成绩查看'])
Z([[2,'&&'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,0]],[[2,'=='],[[6],[[7],[3,'reissueCardData']],[3,'bkStatus']],[1,1]]])
Z([3,'margin-top-sm padding-top-xs border-top-dashed text-xs text-white text-center'])
Z(z[81])
Z([a,[3,'开放补卡时间：'],[[6],[[7],[3,'reissueCardData']],[3,'startTime']],[3,' ~ '],[[6],[[7],[3,'reissueCardData']],[3,'endTime']]])
Z([3,'glass-card status-card bg-gradient-orange margin-bottom shadow-blur padding-lg'])
Z(z[54])
Z(z[55])
Z(z[56])
Z([3,'cuIcon-timefill text-white margin-right-xs'])
Z([3,'font-size:40rpx;'])
Z(z[57])
Z([3,'成绩暂存本地'])
Z(z[66])
Z([3,'opacity:0.9;line-height:1.6;max-width:80%;'])
Z([3,'网络开小差啦 🥺 你的跑步数据已自动保存。'])
Z([3,'稍后去'])
Z([3,'font-weight:bold;border-bottom:1rpx solid rgba(255,255,255,0.6);'])
Z([3,'「我的 → 本地记录」'])
Z([3,'手动提交，若提交失败可人工申诉！'])
Z(z[73])
Z(z[96])
Z([3,'retrySubmit'])
Z([3,'appeal-glass-btn flex-sub margin-right-sm pulse-effect text-center'])
Z([3,'padding:16rpx 0;font-size:28rpx;'])
Z([3,'cuIcon-upload margin-right-xs'])
Z([3,'重新提交'])
Z(z[60])
Z([3,'appeal-glass-btn flex-sub margin-right-sm text-center'])
Z([3,'padding:16rpx 0;'])
Z([3,'人工申诉'])
Z([3,'goToLocalRecords'])
Z([3,'appeal-glass-btn flex-sub text-center'])
Z(z[141])
Z([3,'本地记录'])
Z([3,'glass-card margin-bottom'])
Z([3,'overflow:hidden;'])
Z([[2,'||'],[[2,'=='],[[7],[3,'runType']],[1,0]],[[2,'=='],[[7],[3,'runType']],[1,2]]])
Z([3,'myMap'])
Z([[7],[3,'latitude']])
Z([[7],[3,'longitude']])
Z([[7],[3,'polyline']])
Z([1,16])
Z([3,'width:100%;height:350rpx;border-radius:20rpx;'])
Z([3,'height:180rpx;'])
Z([3,'bottom-action-bar'])
Z([3,'glass-bar flex padding-sm'])
Z([3,'toShare'])
Z([3,'flex-sub ios-btn bg-blue margin-right'])
Z([3,'cuIcon-share margin-right-xs'])
Z([3,'分享战绩'])
Z([3,'goback'])
Z([3,'flex-sub ios-btn bg-gray text-red'])
Z([3,'关闭'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_105_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_105_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_105=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_105=true;
var x=['./pages/run/statement.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_105_1()
var hQ5C=_n('view')
_rz(z,hQ5C,'class',0,e,s,gg)
var oR5C=_n('view')
_rz(z,oR5C,'class',1,e,s,gg)
_(hQ5C,oR5C)
var cS5C=_n('view')
_rz(z,cS5C,'class',2,e,s,gg)
_(hQ5C,cS5C)
_(r,hQ5C)
var oT5C=_n('view')
_rz(z,oT5C,'class',3,e,s,gg)
var aV5C=_mz(z,'view',['class',4,'style',1],[],e,s,gg)
var tW5C=_mz(z,'view',['class',6,'style',1],[],e,s,gg)
var eX5C=_oz(z,8,e,s,gg)
_(tW5C,eX5C)
_(aV5C,tW5C)
_(oT5C,aV5C)
var bY5C=_n('view')
_rz(z,bY5C,'class',9,e,s,gg)
var oZ5C=_n('view')
_rz(z,oZ5C,'class',10,e,s,gg)
var x15C=_n('view')
_rz(z,x15C,'class',11,e,s,gg)
var o25C=_mz(z,'view',['class',12,'style',1],[],e,s,gg)
var f35C=_oz(z,14,e,s,gg)
_(o25C,f35C)
_(x15C,o25C)
var c45C=_mz(z,'view',['class',15,'style',1],[],e,s,gg)
var h55C=_oz(z,17,e,s,gg)
_(c45C,h55C)
_(x15C,c45C)
var o65C=_mz(z,'view',['class',18,'style',1],[],e,s,gg)
var c75C=_oz(z,20,e,s,gg)
_(o65C,c75C)
_(x15C,o65C)
_(oZ5C,x15C)
var o85C=_n('view')
_rz(z,o85C,'class',21,e,s,gg)
var l95C=_n('text')
_rz(z,l95C,'class',22,e,s,gg)
var a05C=_oz(z,23,e,s,gg)
_(l95C,a05C)
_(o85C,l95C)
_(oZ5C,o85C)
_(bY5C,oZ5C)
var tA6C=_n('view')
_rz(z,tA6C,'class',24,e,s,gg)
var eB6C=_n('view')
_rz(z,eB6C,'class',25,e,s,gg)
var bC6C=_n('text')
_rz(z,bC6C,'class',26,e,s,gg)
var oD6C=_oz(z,27,e,s,gg)
_(bC6C,oD6C)
_(eB6C,bC6C)
var xE6C=_mz(z,'text',['class',28,'style',1],[],e,s,gg)
var oF6C=_oz(z,30,e,s,gg)
_(xE6C,oF6C)
_(eB6C,xE6C)
_(tA6C,eB6C)
_(bY5C,tA6C)
var fG6C=_n('view')
_rz(z,fG6C,'class',31,e,s,gg)
var cH6C=_n('view')
_rz(z,cH6C,'class',32,e,s,gg)
var hI6C=_n('text')
_rz(z,hI6C,'class',33,e,s,gg)
var oJ6C=_oz(z,34,e,s,gg)
_(hI6C,oJ6C)
_(cH6C,hI6C)
var cK6C=_n('text')
_rz(z,cK6C,'class',35,e,s,gg)
var oL6C=_oz(z,36,e,s,gg)
_(cK6C,oL6C)
_(cH6C,cK6C)
_(fG6C,cH6C)
var lM6C=_n('view')
_rz(z,lM6C,'class',37,e,s,gg)
var aN6C=_n('text')
_rz(z,aN6C,'class',38,e,s,gg)
var tO6C=_oz(z,39,e,s,gg)
_(aN6C,tO6C)
_(lM6C,aN6C)
var eP6C=_n('text')
_rz(z,eP6C,'class',40,e,s,gg)
var bQ6C=_oz(z,41,e,s,gg)
_(eP6C,bQ6C)
_(lM6C,eP6C)
_(fG6C,lM6C)
var oR6C=_n('view')
_rz(z,oR6C,'class',42,e,s,gg)
var xS6C=_n('text')
_rz(z,xS6C,'class',43,e,s,gg)
var oT6C=_oz(z,44,e,s,gg)
_(xS6C,oT6C)
_(oR6C,xS6C)
var fU6C=_n('text')
_rz(z,fU6C,'class',45,e,s,gg)
var cV6C=_oz(z,46,e,s,gg)
_(fU6C,cV6C)
_(oR6C,fU6C)
_(fG6C,oR6C)
_(bY5C,fG6C)
var hW6C=_n('view')
_rz(z,hW6C,'class',47,e,s,gg)
var oX6C=_n('text')
_rz(z,oX6C,'class',48,e,s,gg)
var cY6C=_oz(z,49,e,s,gg)
_(oX6C,cY6C)
_(hW6C,oX6C)
var oZ6C=_n('text')
_rz(z,oZ6C,'class',50,e,s,gg)
var l16C=_oz(z,51,e,s,gg)
_(oZ6C,l16C)
_(hW6C,oZ6C)
_(bY5C,hW6C)
_(oT5C,bY5C)
var lU5C=_v()
_(oT5C,lU5C)
if(_oz(z,52,e,s,gg)){lU5C.wxVkey=1
var a26C=_n('view')
_rz(z,a26C,'class',53,e,s,gg)
var e46C=_n('view')
_rz(z,e46C,'class',54,e,s,gg)
var x76C=_mz(z,'view',['class',55,'style',1],[],e,s,gg)
var f96C=_n('text')
_rz(z,f96C,'class',57,e,s,gg)
var c06C=_oz(z,58,e,s,gg)
_(f96C,c06C)
_(x76C,f96C)
var o86C=_v()
_(x76C,o86C)
if(_oz(z,59,e,s,gg)){o86C.wxVkey=1
var hA7C=_mz(z,'view',['bindtap',60,'class',1],[],e,s,gg)
var oB7C=_oz(z,62,e,s,gg)
_(hA7C,oB7C)
var cC7C=_mz(z,'text',['class',63,'style',1],[],e,s,gg)
_(hA7C,cC7C)
_(o86C,hA7C)
}
o86C.wxXCkey=1
_(e46C,x76C)
var b56C=_v()
_(e46C,b56C)
if(_oz(z,65,e,s,gg)){b56C.wxVkey=1
var oD7C=_mz(z,'view',['class',66,'style',1],[],e,s,gg)
var lE7C=_oz(z,68,e,s,gg)
_(oD7C,lE7C)
_(b56C,oD7C)
}
var o66C=_v()
_(e46C,o66C)
if(_oz(z,69,e,s,gg)){o66C.wxVkey=1
var aF7C=_mz(z,'view',['class',70,'style',1],[],e,s,gg)
var tG7C=_oz(z,72,e,s,gg)
_(aF7C,tG7C)
_(o66C,aF7C)
}
b56C.wxXCkey=1
o66C.wxXCkey=1
_(a26C,e46C)
var eH7C=_n('view')
_rz(z,eH7C,'class',73,e,s,gg)
_(a26C,eH7C)
var t36C=_v()
_(a26C,t36C)
if(_oz(z,74,e,s,gg)){t36C.wxVkey=1
var bI7C=_mz(z,'view',['class',75,'style',1],[],e,s,gg)
var oJ7C=_n('view')
_rz(z,oJ7C,'class',77,e,s,gg)
var xK7C=_n('view')
_rz(z,xK7C,'class',78,e,s,gg)
var oL7C=_oz(z,79,e,s,gg)
_(xK7C,oL7C)
_(oJ7C,xK7C)
var fM7C=_mz(z,'view',['class',80,'style',1],[],e,s,gg)
var cN7C=_oz(z,82,e,s,gg)
_(fM7C,cN7C)
_(oJ7C,fM7C)
_(bI7C,oJ7C)
var hO7C=_n('view')
_rz(z,hO7C,'class',83,e,s,gg)
var oP7C=_n('view')
_rz(z,oP7C,'class',84,e,s,gg)
var cQ7C=_oz(z,85,e,s,gg)
_(oP7C,cQ7C)
_(hO7C,oP7C)
var oR7C=_mz(z,'view',['class',86,'style',1],[],e,s,gg)
var lS7C=_oz(z,88,e,s,gg)
_(oR7C,lS7C)
_(hO7C,oR7C)
_(bI7C,hO7C)
var aT7C=_n('view')
_rz(z,aT7C,'class',89,e,s,gg)
var tU7C=_n('view')
_rz(z,tU7C,'class',90,e,s,gg)
var eV7C=_oz(z,91,e,s,gg)
_(tU7C,eV7C)
_(aT7C,tU7C)
var bW7C=_mz(z,'view',['class',92,'style',1],[],e,s,gg)
var oX7C=_oz(z,94,e,s,gg)
_(bW7C,oX7C)
_(aT7C,bW7C)
_(bI7C,aT7C)
_(t36C,bI7C)
}
var xY7C=_n('view')
_rz(z,xY7C,'class',95,e,s,gg)
var f17C=_n('view')
_rz(z,f17C,'class',96,e,s,gg)
var c27C=_n('view')
_rz(z,c27C,'class',97,e,s,gg)
var o47C=_n('text')
_rz(z,o47C,'class',98,e,s,gg)
_(c27C,o47C)
var h37C=_v()
_(c27C,h37C)
if(_oz(z,99,e,s,gg)){h37C.wxVkey=1
var c57C=_oz(z,100,e,s,gg)
_(h37C,c57C)
}
else if(_oz(z,101,e,s,gg)){h37C.wxVkey=2
var o67C=_oz(z,102,e,s,gg)
_(h37C,o67C)
}
else{h37C.wxVkey=3
var l77C=_oz(z,103,e,s,gg)
_(h37C,l77C)
}
h37C.wxXCkey=1
_(f17C,c27C)
var a87C=_mz(z,'view',['class',104,'style',1],[],e,s,gg)
var t97C=_v()
_(a87C,t97C)
if(_oz(z,106,e,s,gg)){t97C.wxVkey=1
var e07C=_v()
_(t97C,e07C)
if(_oz(z,107,e,s,gg)){e07C.wxVkey=1
var bA8C=_n('view')
var oB8C=_oz(z,108,e,s,gg)
_(bA8C,oB8C)
var xC8C=_n('text')
_rz(z,xC8C,'class',109,e,s,gg)
var oD8C=_oz(z,110,e,s,gg)
_(xC8C,oD8C)
_(bA8C,xC8C)
_(e07C,bA8C)
}
else{e07C.wxVkey=2
var fE8C=_n('view')
var cF8C=_oz(z,111,e,s,gg)
_(fE8C,cF8C)
_(e07C,fE8C)
}
e07C.wxXCkey=1
}
else{t97C.wxVkey=2
var hG8C=_n('text')
var oH8C=_oz(z,112,e,s,gg)
_(hG8C,oH8C)
_(t97C,hG8C)
}
t97C.wxXCkey=1
_(f17C,a87C)
_(xY7C,f17C)
var oZ7C=_v()
_(xY7C,oZ7C)
if(_oz(z,113,e,s,gg)){oZ7C.wxVkey=1
var cI8C=_mz(z,'view',['class',114,'style',1],[],e,s,gg)
var oJ8C=_oz(z,116,e,s,gg)
_(cI8C,oJ8C)
_(oZ7C,cI8C)
}
oZ7C.wxXCkey=1
_(a26C,xY7C)
t36C.wxXCkey=1
_(lU5C,a26C)
}
else{lU5C.wxVkey=2
var lK8C=_n('view')
_rz(z,lK8C,'class',117,e,s,gg)
var aL8C=_n('view')
_rz(z,aL8C,'class',118,e,s,gg)
var tM8C=_mz(z,'view',['class',119,'style',1],[],e,s,gg)
var eN8C=_mz(z,'text',['class',121,'style',1],[],e,s,gg)
_(tM8C,eN8C)
var bO8C=_n('text')
_rz(z,bO8C,'class',123,e,s,gg)
var oP8C=_oz(z,124,e,s,gg)
_(bO8C,oP8C)
_(tM8C,bO8C)
_(aL8C,tM8C)
var xQ8C=_mz(z,'view',['class',125,'style',1],[],e,s,gg)
var oR8C=_oz(z,127,e,s,gg)
_(xQ8C,oR8C)
var fS8C=_n('br')
_(xQ8C,fS8C)
var cT8C=_oz(z,128,e,s,gg)
_(xQ8C,cT8C)
var hU8C=_n('text')
_rz(z,hU8C,'style',129,e,s,gg)
var oV8C=_oz(z,130,e,s,gg)
_(hU8C,oV8C)
_(xQ8C,hU8C)
var cW8C=_oz(z,131,e,s,gg)
_(xQ8C,cW8C)
_(aL8C,xQ8C)
_(lK8C,aL8C)
var oX8C=_n('view')
_rz(z,oX8C,'class',132,e,s,gg)
_(lK8C,oX8C)
var lY8C=_n('view')
_rz(z,lY8C,'class',133,e,s,gg)
var aZ8C=_mz(z,'view',['bindtap',134,'class',1,'style',2],[],e,s,gg)
var t18C=_n('text')
_rz(z,t18C,'class',137,e,s,gg)
_(aZ8C,t18C)
var e28C=_oz(z,138,e,s,gg)
_(aZ8C,e28C)
_(lY8C,aZ8C)
var b38C=_mz(z,'view',['bindtap',139,'class',1,'style',2],[],e,s,gg)
var o48C=_oz(z,142,e,s,gg)
_(b38C,o48C)
_(lY8C,b38C)
var x58C=_mz(z,'view',['bindtap',143,'class',1,'style',2],[],e,s,gg)
var o68C=_oz(z,146,e,s,gg)
_(x58C,o68C)
_(lY8C,x58C)
_(lK8C,lY8C)
_(lU5C,lK8C)
}
var f78C=_mz(z,'view',['class',147,'style',1],[],e,s,gg)
var c88C=_v()
_(f78C,c88C)
if(_oz(z,149,e,s,gg)){c88C.wxVkey=1
var h98C=_mz(z,'map',['showLocation',-1,'id',150,'latitude',1,'longitude',2,'polyline',3,'scale',4,'style',5],[],e,s,gg)
_(c88C,h98C)
}
c88C.wxXCkey=1
_(oT5C,f78C)
var o08C=_n('view')
_rz(z,o08C,'style',156,e,s,gg)
_(oT5C,o08C)
lU5C.wxXCkey=1
_(r,oT5C)
var cA9C=_n('view')
_rz(z,cA9C,'class',157,e,s,gg)
var oB9C=_n('view')
_rz(z,oB9C,'class',158,e,s,gg)
var lC9C=_mz(z,'button',['bindtap',159,'class',1],[],e,s,gg)
var aD9C=_n('text')
_rz(z,aD9C,'class',161,e,s,gg)
_(lC9C,aD9C)
var tE9C=_oz(z,162,e,s,gg)
_(lC9C,tE9C)
_(oB9C,lC9C)
var eF9C=_mz(z,'button',['bindtap',163,'class',1],[],e,s,gg)
var bG9C=_oz(z,165,e,s,gg)
_(eF9C,bG9C)
_(oB9C,eF9C)
_(cA9C,oB9C)
_(r,cA9C)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_105";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_105();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/run/statement.wxml'] = [$gwx_XC_105, './pages/run/statement.wxml'];else __wxAppCode__['pages/run/statement.wxml'] = $gwx_XC_105( './pages/run/statement.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/run/statement.wxss']=setCssToHead(["body{background-color:#f2f2f7;font-family:-apple-system,BlinkMacSystemFont,Helvetica Neue,Helvetica,Segoe UI,Arial,Roboto,PingFang SC,sans-serif}\n.",[1],"background-blobs{background:#f5f7fa;height:100vh;left:0;pointer-events:none;position:fixed;top:0;width:100%;z-index:-1}\n.",[1],"blob{border-radius:50%;-webkit-filter:blur(50px);filter:blur(50px);opacity:.6;position:absolute}\n.",[1],"blob-1{-webkit-animation:float 10s ease-in-out infinite;animation:float 10s ease-in-out infinite;background:#a0c4ff;height:",[0,400],";left:",[0,-50],";top:",[0,-100],";width:",[0,400],"}\n.",[1],"blob-2{animation:float 8s ease-in-out infinite reverse;background:#ffccbc;bottom:10%;height:",[0,350],";right:",[0,-50],";width:",[0,350],"}\n@-webkit-keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}@keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}.",[1],"main-container{padding:",[0,30],"}\n.",[1],"nav-placeholder{height:",[0,20],"}\n.",[1],"glass-notice{-webkit-align-items:center;align-items:center;background:rgba(0,122,255,.1);border:1px solid rgba(0,122,255,.2);border-radius:",[0,16],";display:-webkit-flex;display:flex;padding:",[0,16]," ",[0,24],"}\n.",[1],"notice-icon{height:",[0,30],";margin-right:",[0,12],";width:",[0,30],"}\n.",[1],"notice-text{color:#007aff;font-size:",[0,24],"}\n.",[1],"glass-card{backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);background:hsla(0,0%,100%,.15);border:1px solid hsla(0,0%,100%,.8);border-radius:",[0,32],";box-shadow:0 8px 32px 0 rgba(31,38,135,.15);overflow:hidden}\n.",[1],"capsule-tag{background:rgba(0,0,0,.05);border-radius:",[0,100],";display:inline-block;font-size:",[0,24],";padding:",[0,8]," ",[0,20],"}\n@font-face{font-family:DINPro-Regular;src:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/font/DINPro-Regular.otf\x22)}\n.",[1],"din-font{font-family:DINPro-Regular,-apple-system,sans-serif}\n.",[1],"hero-number{color:#1c1c1e;font-size:",[0,120],";font-weight:700;letter-spacing:-2px;line-height:1}\n.",[1],"grid-stats{-webkit-justify-content:space-around;justify-content:space-around;margin-top:",[0,40],"}\n.",[1],"grid-stats,.",[1],"stat-item{display:-webkit-flex;display:flex}\n.",[1],"stat-item{-webkit-align-items:center;align-items:center;-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"stat-val{color:#1c1c1e;font-size:",[0,40],";font-weight:600}\n.",[1],"stat-label{color:#8e8e93;font-size:",[0,22],";margin-top:",[0,6],"}\n.",[1],"status-card{border-radius:",[0,32],";overflow:hidden;padding:",[0,30],";position:relative}\n.",[1],"bg-gradient-blue{background:linear-gradient(135deg,#007aff,#00c6ff);box-shadow:0 ",[0,8]," ",[0,24]," rgba(0,122,255,.3)}\n.",[1],"bg-gradient-red{background:linear-gradient(135deg,#ff3b30,#ff9500);box-shadow:0 ",[0,8]," ",[0,24]," rgba(255,59,48,.3)}\n.",[1],"status-icon{height:",[0,36],";margin-right:",[0,12],";width:",[0,36],"}\n.",[1],"border-top-white{border-top:",[0,1]," solid hsla(0,0%,100%,.3)}\n.",[1],"bottom-action-bar{bottom:",[0,40],";left:0;padding:0 ",[0,30],";position:fixed;width:100%;z-index:100}\n.",[1],"glass-bar{-webkit-backdrop-filter:blur(20px);backdrop-filter:blur(20px);background:hsla(0,0%,100%,.85);border:1px solid hsla(0,0%,100%,.5);border-radius:",[0,100],";box-shadow:0 ",[0,10]," ",[0,40]," rgba(0,0,0,.1)}\n.",[1],"ios-btn{-webkit-align-items:center;align-items:center;border-radius:",[0,100],";display:-webkit-flex;display:flex;font-size:",[0,30],";font-weight:600;height:",[0,88],";-webkit-justify-content:center;justify-content:center;line-height:",[0,88],"}\n.",[1],"ios-btn::after{border:none}\n.",[1],"bg-blue{background:#007aff;color:#fff}\n.",[1],"bg-gray{background:rgba(0,0,0,.05);color:#333}\n.",[1],"flex{display:-webkit-flex;display:flex}\n.",[1],"justify-between{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"justify-center{-webkit-justify-content:center;justify-content:center}\n.",[1],"align-center{-webkit-align-items:center;align-items:center}\n.",[1],"align-baseline{-webkit-align-items:baseline;align-items:baseline}\n.",[1],"text-center{text-align:center}\n.",[1],"text-right{text-align:right}\n.",[1],"flex-sub{-webkit-flex:1;flex:1}\n.",[1],"relative{position:relative}\n.",[1],"margin-bottom{margin-bottom:",[0,30],"}\n.",[1],"margin-bottom-sm{margin-bottom:",[0,20],"}\n.",[1],"margin-tb-lg{margin:",[0,40]," 0}\n.",[1],"margin-top{margin-top:",[0,30],"}\n.",[1],"margin-top-xs{margin-top:",[0,10],"}\n.",[1],"margin-top-sm{margin-top:",[0,20],"}\n.",[1],"margin-left-sm{margin-left:",[0,20],"}\n.",[1],"margin-left-xs{margin-left:",[0,10],"}\n.",[1],"margin-right{margin-right:",[0,20],"}\n.",[1],"padding-lg{padding:",[0,40],"}\n.",[1],"padding-sm{padding:",[0,20],"}\n.",[1],"padding-xs{padding:",[0,10],"}\n.",[1],"padding-top-xs{padding-top:",[0,10],"}\n.",[1],"pt-sm{padding-top:",[0,20],"}\n.",[1],"border-left{border-left:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"border-right{border-right:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"border-top{border-top:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"text-xl{font-size:",[0,36],"}\n.",[1],"text-lg{font-size:",[0,32],"}\n.",[1],"text-sm{font-size:",[0,26],"}\n.",[1],"text-xs{font-size:",[0,22],"}\n.",[1],"text-bold{font-weight:600}\n.",[1],"text-gray{color:#8e8e93}\n.",[1],"text-white{color:#fff}\n.",[1],"text-orange{color:#ff9500}\n.",[1],"text-green{color:#34c759}\n.",[1],"text-red{color:#ff3b30}\n.",[1],"fade-in{-webkit-animation:fadeIn .8s ease-out forwards;animation:fadeIn .8s ease-out forwards;opacity:0;-webkit-transform:translateY(",[0,30],");transform:translateY(",[0,30],")}\n@-webkit-keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"user-pill-glass{background:hsla(0,0%,100%,.25);border:",[0,1]," solid hsla(0,0%,100%,.4);border-radius:",[0,32],";box-sizing:border-box;height:100%;padding:",[0,6]," ",[0,24]," ",[0,6]," ",[0,10],"}\n.",[1],"border-top-white-light{background-color:hsla(0,0%,100%,.2);height:1px;width:100%}\n.",[1],"bg-white-transparent{background-color:hsla(0,0%,100%,.15)}\n.",[1],"border-top-dashed{border-top:1px dashed hsla(0,0%,100%,.3)}\n.",[1],"text-xxl{font-size:",[0,44],"}\n.",[1],"text-md{font-size:",[0,28],"}\n.",[1],"appeal-glass-btn{-webkit-align-items:center;align-items:center;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);background:hsla(0,0%,100%,.25);border:1px solid hsla(0,0%,100%,.6);border-radius:",[0,100],";box-shadow:0 ",[0,4]," ",[0,12]," rgba(0,0,0,.08);color:#fff;display:-webkit-flex;display:flex;font-size:",[0,26],";font-weight:500;-webkit-justify-content:center;justify-content:center;padding:",[0,8]," ",[0,28],";transition:all .2s ease}\n.",[1],"appeal-glass-btn:active{background:hsla(0,0%,100%,.4);-webkit-transform:scale(.95);transform:scale(.95)}\n@-webkit-keyframes pulse-white{0%{box-shadow:0 0 0 0 hsla(0,0%,100%,.6)}\n70%{box-shadow:0 0 0 ",[0,15]," hsla(0,0%,100%,0)}\n100%{box-shadow:0 0 0 0 hsla(0,0%,100%,0)}\n}@keyframes pulse-white{0%{box-shadow:0 0 0 0 hsla(0,0%,100%,.6)}\n70%{box-shadow:0 0 0 ",[0,15]," hsla(0,0%,100%,0)}\n100%{box-shadow:0 0 0 0 hsla(0,0%,100%,0)}\n}.",[1],"pulse-effect{-webkit-animation:pulse-white 2s infinite;animation:pulse-white 2s infinite}\n.",[1],"bg-gradient-orange{background:linear-gradient(135deg,#ff9500,#fc0);box-shadow:0 ",[0,8]," ",[0,24]," rgba(255,149,0,.35)}\n.",[1],"bg-gradient-orange .",[1],"appeal-glass-btn{background:hsla(0,0%,100%,.2);font-size:",[0,24],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/run/statement.wxss:1:1)",{path:"./pages/run/statement.wxss"});
}