$gwx_XC_89=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_89 || [];
function gz$gwx_XC_89_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_89_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_89_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_89_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'background-blobs'])
Z([3,'blob blob-1'])
Z([3,'blob blob-2'])
Z([3,'nav-placeholder'])
Z([3,'main-container fade-in'])
Z([3,'glass-card padding-xl text-center margin-bottom'])
Z([3,'text-gray text-sm margin-bottom-xs'])
Z([3,'您的 BMI 指数'])
Z([3,'hero-number din-font'])
Z([a,[3,'color:'],[[7],[3,'statusColor']],[3,';']])
Z([a,[[7],[3,'bmi']]])
Z([3,'margin-top-sm'])
Z([3,'status-capsule'])
Z([a,[3,'background:'],[[7],[3,'statusBgColor']],[3,';color:'],z[9][2],z[9][3]])
Z([a,[[7],[3,'statusText']]])
Z([3,'margin-top text-gray text-xs'])
Z([3,'BMI \x3d 体重(kg) / 身高²(m²)'])
Z([3,'glass-card overflow-hidden'])
Z([3,'padding-lr padding-top-sm padding-bottom-sm border-bottom'])
Z([3,'text-bold text-black text-lg'])
Z([3,'参考标准'])
Z([3,'range-list'])
Z([a,[3,'range-item '],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,0]],[1,'active-row'],[1,'']]])
Z([3,'flex align-center'])
Z([3,'dot bg-blue'])
Z([3,'text-black'])
Z([3,'体重过轻'])
Z([3,'din-font text-gray'])
Z([3,'BMI  小于 18.5'])
Z([a,z[22][1],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,1]],[1,'active-row'],[1,'']]])
Z(z[23])
Z([3,'dot bg-green'])
Z(z[25])
Z([3,'正常范围'])
Z(z[27])
Z([3,'18.5 ~ 23.9'])
Z([a,z[22][1],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,2]],[1,'active-row'],[1,'']]])
Z(z[23])
Z([3,'dot bg-yellow'])
Z(z[25])
Z([3,'体重过重'])
Z(z[27])
Z([3,'24.0 ~ 26.9'])
Z([a,z[22][1],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,3]],[1,'active-row'],[1,'']]])
Z(z[23])
Z([3,'dot bg-orange'])
Z(z[25])
Z([3,'轻度肥胖'])
Z(z[27])
Z([3,'27.0 ~ 29.9'])
Z([a,z[22][1],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,4]],[1,'active-row'],[1,'']]])
Z(z[23])
Z([3,'dot bg-red'])
Z(z[25])
Z([3,'中度肥胖'])
Z(z[27])
Z([3,'30.0 ~ 34.9'])
Z([a,z[22][1],[[2,'?:'],[[2,'==='],[[7],[3,'currentLevel']],[1,5]],[1,'active-row'],[1,'']]])
Z(z[23])
Z([3,'dot bg-dark-red'])
Z(z[25])
Z([3,'重度肥胖'])
Z(z[27])
Z([3,'BMI ≥ 35'])
Z([3,'text-center margin-top text-gray text-xs'])
Z([3,'*数据仅供参考，请以专业医疗建议为准'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_89_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_89_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_89=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_89=true;
var x=['./pages/bmi/index.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_89_1()
var cA3B=_n('view')
_rz(z,cA3B,'class',0,e,s,gg)
var oB3B=_n('view')
_rz(z,oB3B,'class',1,e,s,gg)
_(cA3B,oB3B)
var lC3B=_n('view')
_rz(z,lC3B,'class',2,e,s,gg)
_(cA3B,lC3B)
_(r,cA3B)
var aD3B=_n('view')
_rz(z,aD3B,'class',3,e,s,gg)
_(r,aD3B)
var tE3B=_n('view')
_rz(z,tE3B,'class',4,e,s,gg)
var eF3B=_n('view')
_rz(z,eF3B,'class',5,e,s,gg)
var bG3B=_n('view')
_rz(z,bG3B,'class',6,e,s,gg)
var oH3B=_oz(z,7,e,s,gg)
_(bG3B,oH3B)
_(eF3B,bG3B)
var xI3B=_mz(z,'view',['class',8,'style',1],[],e,s,gg)
var oJ3B=_oz(z,10,e,s,gg)
_(xI3B,oJ3B)
_(eF3B,xI3B)
var fK3B=_n('view')
_rz(z,fK3B,'class',11,e,s,gg)
var cL3B=_mz(z,'view',['class',12,'style',1],[],e,s,gg)
var hM3B=_oz(z,14,e,s,gg)
_(cL3B,hM3B)
_(fK3B,cL3B)
_(eF3B,fK3B)
var oN3B=_n('view')
_rz(z,oN3B,'class',15,e,s,gg)
var cO3B=_oz(z,16,e,s,gg)
_(oN3B,cO3B)
_(eF3B,oN3B)
_(tE3B,eF3B)
var oP3B=_n('view')
_rz(z,oP3B,'class',17,e,s,gg)
var lQ3B=_n('view')
_rz(z,lQ3B,'class',18,e,s,gg)
var aR3B=_n('text')
_rz(z,aR3B,'class',19,e,s,gg)
var tS3B=_oz(z,20,e,s,gg)
_(aR3B,tS3B)
_(lQ3B,aR3B)
_(oP3B,lQ3B)
var eT3B=_n('view')
_rz(z,eT3B,'class',21,e,s,gg)
var bU3B=_n('view')
_rz(z,bU3B,'class',22,e,s,gg)
var oV3B=_n('view')
_rz(z,oV3B,'class',23,e,s,gg)
var xW3B=_n('view')
_rz(z,xW3B,'class',24,e,s,gg)
_(oV3B,xW3B)
var oX3B=_n('text')
_rz(z,oX3B,'class',25,e,s,gg)
var fY3B=_oz(z,26,e,s,gg)
_(oX3B,fY3B)
_(oV3B,oX3B)
_(bU3B,oV3B)
var cZ3B=_n('text')
_rz(z,cZ3B,'class',27,e,s,gg)
var h13B=_oz(z,28,e,s,gg)
_(cZ3B,h13B)
_(bU3B,cZ3B)
_(eT3B,bU3B)
var o23B=_n('view')
_rz(z,o23B,'class',29,e,s,gg)
var c33B=_n('view')
_rz(z,c33B,'class',30,e,s,gg)
var o43B=_n('view')
_rz(z,o43B,'class',31,e,s,gg)
_(c33B,o43B)
var l53B=_n('text')
_rz(z,l53B,'class',32,e,s,gg)
var a63B=_oz(z,33,e,s,gg)
_(l53B,a63B)
_(c33B,l53B)
_(o23B,c33B)
var t73B=_n('text')
_rz(z,t73B,'class',34,e,s,gg)
var e83B=_oz(z,35,e,s,gg)
_(t73B,e83B)
_(o23B,t73B)
_(eT3B,o23B)
var b93B=_n('view')
_rz(z,b93B,'class',36,e,s,gg)
var o03B=_n('view')
_rz(z,o03B,'class',37,e,s,gg)
var xA4B=_n('view')
_rz(z,xA4B,'class',38,e,s,gg)
_(o03B,xA4B)
var oB4B=_n('text')
_rz(z,oB4B,'class',39,e,s,gg)
var fC4B=_oz(z,40,e,s,gg)
_(oB4B,fC4B)
_(o03B,oB4B)
_(b93B,o03B)
var cD4B=_n('text')
_rz(z,cD4B,'class',41,e,s,gg)
var hE4B=_oz(z,42,e,s,gg)
_(cD4B,hE4B)
_(b93B,cD4B)
_(eT3B,b93B)
var oF4B=_n('view')
_rz(z,oF4B,'class',43,e,s,gg)
var cG4B=_n('view')
_rz(z,cG4B,'class',44,e,s,gg)
var oH4B=_n('view')
_rz(z,oH4B,'class',45,e,s,gg)
_(cG4B,oH4B)
var lI4B=_n('text')
_rz(z,lI4B,'class',46,e,s,gg)
var aJ4B=_oz(z,47,e,s,gg)
_(lI4B,aJ4B)
_(cG4B,lI4B)
_(oF4B,cG4B)
var tK4B=_n('text')
_rz(z,tK4B,'class',48,e,s,gg)
var eL4B=_oz(z,49,e,s,gg)
_(tK4B,eL4B)
_(oF4B,tK4B)
_(eT3B,oF4B)
var bM4B=_n('view')
_rz(z,bM4B,'class',50,e,s,gg)
var oN4B=_n('view')
_rz(z,oN4B,'class',51,e,s,gg)
var xO4B=_n('view')
_rz(z,xO4B,'class',52,e,s,gg)
_(oN4B,xO4B)
var oP4B=_n('text')
_rz(z,oP4B,'class',53,e,s,gg)
var fQ4B=_oz(z,54,e,s,gg)
_(oP4B,fQ4B)
_(oN4B,oP4B)
_(bM4B,oN4B)
var cR4B=_n('text')
_rz(z,cR4B,'class',55,e,s,gg)
var hS4B=_oz(z,56,e,s,gg)
_(cR4B,hS4B)
_(bM4B,cR4B)
_(eT3B,bM4B)
var oT4B=_n('view')
_rz(z,oT4B,'class',57,e,s,gg)
var cU4B=_n('view')
_rz(z,cU4B,'class',58,e,s,gg)
var oV4B=_n('view')
_rz(z,oV4B,'class',59,e,s,gg)
_(cU4B,oV4B)
var lW4B=_n('text')
_rz(z,lW4B,'class',60,e,s,gg)
var aX4B=_oz(z,61,e,s,gg)
_(lW4B,aX4B)
_(cU4B,lW4B)
_(oT4B,cU4B)
var tY4B=_n('text')
_rz(z,tY4B,'class',62,e,s,gg)
var eZ4B=_oz(z,63,e,s,gg)
_(tY4B,eZ4B)
_(oT4B,tY4B)
_(eT3B,oT4B)
_(oP3B,eT3B)
_(tE3B,oP3B)
var b14B=_n('view')
_rz(z,b14B,'class',64,e,s,gg)
var o24B=_oz(z,65,e,s,gg)
_(b14B,o24B)
_(tE3B,b14B)
_(r,tE3B)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_89";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_89();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/bmi/index.wxml'] = [$gwx_XC_89, './pages/bmi/index.wxml'];else __wxAppCode__['pages/bmi/index.wxml'] = $gwx_XC_89( './pages/bmi/index.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/bmi/index.wxss']=setCssToHead(["body{background-color:#f2f2f7;font-family:-apple-system,BlinkMacSystemFont,Helvetica Neue,Helvetica,Segoe UI,Arial,Roboto,PingFang SC,sans-serif}\n.",[1],"background-blobs{background:#f5f7fa;height:100vh;left:0;pointer-events:none;position:fixed;top:0;width:100%;z-index:-1}\n.",[1],"blob{border-radius:50%;-webkit-filter:blur(60px);filter:blur(60px);opacity:.6;position:absolute}\n.",[1],"blob-1{-webkit-animation:float 10s ease-in-out infinite;animation:float 10s ease-in-out infinite;background:#a0c4ff;height:",[0,400],";right:",[0,-50],";top:",[0,-100],";width:",[0,400],"}\n.",[1],"blob-2{animation:float 8s ease-in-out infinite reverse;background:#ffccbc;bottom:20%;height:",[0,350],";left:",[0,-50],";width:",[0,350],"}\n@-webkit-keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}@keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}.",[1],"main-container{padding:",[0,30],"}\n.",[1],"nav-placeholder{height:",[0,20],"}\n.",[1],"glass-card{backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);background:hsla(0,0%,100%,.75);border:1px solid hsla(0,0%,100%,.6);border-radius:",[0,32],";box-shadow:0 ",[0,8]," ",[0,32]," rgba(0,0,0,.04)}\n.",[1],"overflow-hidden{overflow:hidden}\n@font-face{font-family:DINPro-Regular;src:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/font/DINPro-Regular.otf\x22)}\n.",[1],"din-font{font-family:DINPro-Regular,-apple-system,sans-serif}\n.",[1],"hero-number{font-size:",[0,100],";font-weight:700;letter-spacing:-2px;line-height:1.1}\n.",[1],"status-capsule{border-radius:",[0,100],";display:inline-block;font-size:",[0,28],";font-weight:600;padding:",[0,8]," ",[0,24],"}\n.",[1],"range-item{-webkit-align-items:center;align-items:center;border-bottom:",[0,1]," solid rgba(0,0,0,.05);display:-webkit-flex;display:flex;font-size:",[0,28],";-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,24]," ",[0,30],";transition:background .3s}\n.",[1],"range-item:last-child{border-bottom:none}\n.",[1],"active-row{background:rgba(0,122,255,.08)}\n.",[1],"active-row .",[1],"text-black{font-weight:600}\n.",[1],"dot{border-radius:50%;height:",[0,16],";margin-right:",[0,16],";width:",[0,16],"}\n.",[1],"bg-blue{background:#007aff}\n.",[1],"bg-green{background:#34c759}\n.",[1],"bg-yellow{background:#fc0}\n.",[1],"bg-orange{background:#ff9500}\n.",[1],"bg-red{background:#ff3b30}\n.",[1],"bg-dark-red{background:#580c08}\n.",[1],"text-center{text-align:center}\n.",[1],"text-bold{font-weight:600}\n.",[1],"text-sm{font-size:",[0,26],"}\n.",[1],"text-xs{font-size:",[0,22],"}\n.",[1],"text-lg{font-size:",[0,32],"}\n.",[1],"text-gray{color:#8e8e93}\n.",[1],"text-black{color:#1c1c1e}\n.",[1],"flex{display:-webkit-flex;display:flex}\n.",[1],"align-center{-webkit-align-items:center;align-items:center}\n.",[1],"margin-bottom{margin-bottom:",[0,30],"}\n.",[1],"margin-bottom-xs{margin-bottom:",[0,10],"}\n.",[1],"margin-top{margin-top:",[0,30],"}\n.",[1],"margin-top-sm{margin-top:",[0,20],"}\n.",[1],"padding-xl{padding:",[0,50],"}\n.",[1],"padding-lr{padding-left:",[0,30],";padding-right:",[0,30],"}\n.",[1],"padding-top-sm{padding-top:",[0,20],"}\n.",[1],"padding-bottom-sm{padding-bottom:",[0,20],"}\n.",[1],"border-bottom{border-bottom:",[0,1]," solid rgba(0,0,0,.05)}\n.",[1],"fade-in{-webkit-animation:fadeIn .6s ease-out forwards;animation:fadeIn .6s ease-out forwards;opacity:0;-webkit-transform:translateY(",[0,20],");transform:translateY(",[0,20],")}\n@-webkit-keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/bmi/index.wxss:1:1)",{path:"./pages/bmi/index.wxss"});
}