$gwx_XC_82=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_82 || [];
function gz$gwx_XC_82_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_82_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_82_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_82_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'background-blobs'])
Z([3,'blob blob-1'])
Z([3,'blob blob-2'])
Z([3,'nav-placeholder'])
Z([3,'main-container fade-in'])
Z([3,'header-section'])
Z([3,'text-xxl text-bold text-black'])
Z([3,'常见问题'])
Z([3,'text-sm text-gray margin-top-xs block'])
Z([3,'Help Center'])
Z([3,'diagnostic-card'])
Z([3,'card-header flex align-center justify-between'])
Z([3,'flex align-center'])
Z([3,'card-icon'])
Z([3,'https://img.icons8.com/ios-filled/50/007aff/compass.png'])
Z([3,'text-bold text-black'])
Z([3,'font-size:32rpx;'])
Z([3,'定位自检中心'])
Z([a,[3,'status-badge '],[[2,'?:'],[[2,'&&'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'auth']],[1,'authorized']],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'systemGPS']],[1,'on']]],[1,'status-ok'],[1,'status-warn']]])
Z([a,[[2,'?:'],[[2,'&&'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'auth']],[1,'authorized']],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'systemGPS']],[1,'on']]],[1,'正常'],[1,'异常']]])
Z([3,'status-row'])
Z([3,'status-item'])
Z([3,'status-label'])
Z([3,'微信授权'])
Z([a,[3,'status-value '],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'auth']],[1,'authorized']],[1,'text-green'],[1,'text-red']]])
Z([a,[3,'\n          '],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'auth']],[1,'authorized']],[1,'已授权'],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'auth']],[1,'denied']],[1,'未授权'],[1,'未知']]],[3,'\n        ']])
Z(z[21])
Z(z[22])
Z([3,'系统GPS'])
Z([a,z[24][1],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'systemGPS']],[1,'on']],[1,'text-green'],[1,'text-red']]])
Z([a,z[25][1],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'systemGPS']],[1,'on']],[1,'已开启'],[[2,'?:'],[[2,'==='],[[6],[[7],[3,'locationStatus']],[3,'systemGPS']],[1,'off']],[1,'未开启'],[1,'未知']]],z[25][3]])
Z([3,'action-buttons flex'])
Z([3,'startDiagnosis'])
Z([3,'diagnostic-btn primary'])
Z([3,'btn-hover'])
Z([[7],[3,'isChecking']])
Z([a,[[2,'?:'],[[7],[3,'isChecking']],[1,'检测中...'],[1,'一键诊断']]])
Z([3,'openSetting'])
Z([3,'diagnostic-btn secondary'])
Z(z[34])
Z([3,'去授权设置'])
Z([3,'checkLocationStatus'])
Z(z[38])
Z(z[34])
Z([3,'刷新状态'])
Z([[6],[[7],[3,'locationStatus']],[3,'lastCheck']])
Z([3,'last-check'])
Z([3,'text-gray text-sm'])
Z([a,[3,'上次检查: '],[[6],[[7],[3,'locationStatus']],[3,'lastCheck']]])
Z([3,'glass-group margin-top-lg'])
Z([3,'showPopup'])
Z([3,'ios-cell'])
Z([3,'5'])
Z([3,'cell-hover'])
Z(z[12])
Z([3,'cell-icon'])
Z([3,'https://img.icons8.com/ios/50/ff3b30/map-marker.png'])
Z([3,'cell-text'])
Z([3,'定位与里程问题 (必看)'])
Z([3,'cuIcon-right text-gray'])
Z([3,'onClose'])
Z([a,[3,'glass-sheet-mask '],[[2,'?:'],[[7],[3,'show']],[1,'show'],[1,'']]])
Z([a,[3,'glass-sheet '],z[61][2]])
Z(z[60])
Z([3,'drag-handle-bar'])
Z([3,'drag-handle'])
Z([3,'sheet-header'])
Z([3,'text-xl text-bold'])
Z([a,[3,'\n      '],[[2,'?:'],[[2,'=='],[[7],[3,'isActive']],[1,1]],[1,'成绩相关问题'],[[2,'?:'],[[2,'=='],[[7],[3,'isActive']],[1,2]],[1,'注册问题'],[[2,'?:'],[[2,'=='],[[7],[3,'isActive']],[1,3]],[1,'登录问题'],[[2,'?:'],[[2,'=='],[[7],[3,'isActive']],[1,4]],[1,'申诉问题'],[1,'定位与里程问题']]]]],[3,'\n    ']])
Z(z[60])
Z([3,'close-btn'])
Z([3,' text-gray'])
Z(z[16])
Z([3,'✕'])
Z([3,'sheet-content'])
Z([[2,'=='],[[7],[3,'isActive']],[1,1]])
Z([3,'article-box'])
Z([[2,'=='],[[7],[3,'isActive']],[1,2]])
Z(z[76])
Z([[2,'=='],[[7],[3,'isActive']],[1,5]])
Z(z[76])
Z([3,'qa-item'])
Z([3,'q-title'])
Z([3,'1. 为什么跑步没里程，或轨迹变成“大直线穿墙”？'])
Z([3,'a-text'])
Z([3,'这是由于部分安卓手机（特别是'])
Z([3,'text-bold'])
Z([3,'荣耀、华为、Vivo'])
Z([3,'等）的省电策略过于严格。息屏锁屏后，系统会强行掐断微信的GPS定位权限，导致无法记录运动轨迹。'])
Z(z[81])
Z(z[82])
Z([3,'2. 各品牌手机“防杀后台”解决办法'])
Z([3,'notice-box margin-top-sm'])
Z(z[86])
Z([3,'color:#ff3b30;font-size:28rpx;'])
Z([3,'🔥 最简单万能的解决办法：'])
Z([3,'text-red margin-top-xs'])
Z([3,'跑步时不要彻底锁屏（将屏幕亮度调低放入口袋），或者在手机多任务界面给微信【下拉加锁】。'])
Z([3,'a-text margin-top'])
Z(z[86])
Z([3,'color:#007aff;'])
Z([3,'🔵 华为 / 荣耀 (Huawei / Honor)'])
Z([3,'margin-top-xs'])
Z([3,'1. 进入手机【设置】➔【电池】➔【应用耗电管理】➔ 找到【微信】。'])
Z([3,'2. 关闭“自动管理”，开启'])
Z(z[86])
Z([3,'“允许后台活动”'])
Z([3,'。'])
Z(z[98])
Z(z[86])
Z([3,'color:#34c759;'])
Z([3,'🟢 Vivo / OPPO'])
Z(z[102])
Z([3,'1. 进入手机【设置】➔【电池】➔【后台耗电管理】➔ 找到【微信】。'])
Z([3,'2. 设置为'])
Z(z[86])
Z([3,'“允许后台高耗电”'])
Z(z[107])
Z([3,'margin-top-xs text-red'])
Z([3,'3. 若里程依然为0：进入设置 ➔ 应用与权限 ➔ 权限管理 ➔ 微信 ➔ 将位置信息权限改为'])
Z(z[86])
Z([3,'【每次询问】'])
Z([3,'，强制刷新系统定位缓存！'])
Z(z[98])
Z(z[86])
Z([3,'color:#ff9500;'])
Z([3,'🟠 小米 / 红米 (Xiaomi / Redmi)'])
Z(z[102])
Z([3,'1. 进入手机【设置】➔【应用设置】➔【应用管理】➔ 找到【微信】。'])
Z([3,'2. 省电策略选择'])
Z(z[86])
Z([3,'“无限制”'])
Z(z[107])
Z([3,'height:100rpx;'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_82_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_82_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_82=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_82=true;
var x=['./pages/FAQ/index.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_82_1()
var oBVB=_n('view')
_rz(z,oBVB,'class',0,e,s,gg)
var lCVB=_n('view')
_rz(z,lCVB,'class',1,e,s,gg)
_(oBVB,lCVB)
var aDVB=_n('view')
_rz(z,aDVB,'class',2,e,s,gg)
_(oBVB,aDVB)
_(r,oBVB)
var tEVB=_n('view')
_rz(z,tEVB,'class',3,e,s,gg)
_(r,tEVB)
var eFVB=_n('view')
_rz(z,eFVB,'class',4,e,s,gg)
var bGVB=_n('view')
_rz(z,bGVB,'class',5,e,s,gg)
var oHVB=_n('text')
_rz(z,oHVB,'class',6,e,s,gg)
var xIVB=_oz(z,7,e,s,gg)
_(oHVB,xIVB)
_(bGVB,oHVB)
var oJVB=_n('text')
_rz(z,oJVB,'class',8,e,s,gg)
var fKVB=_oz(z,9,e,s,gg)
_(oJVB,fKVB)
_(bGVB,oJVB)
_(eFVB,bGVB)
var cLVB=_n('view')
_rz(z,cLVB,'class',10,e,s,gg)
var oNVB=_n('view')
_rz(z,oNVB,'class',11,e,s,gg)
var cOVB=_n('view')
_rz(z,cOVB,'class',12,e,s,gg)
var oPVB=_mz(z,'image',['class',13,'src',1],[],e,s,gg)
_(cOVB,oPVB)
var lQVB=_mz(z,'text',['class',15,'style',1],[],e,s,gg)
var aRVB=_oz(z,17,e,s,gg)
_(lQVB,aRVB)
_(cOVB,lQVB)
_(oNVB,cOVB)
var tSVB=_n('view')
_rz(z,tSVB,'class',18,e,s,gg)
var eTVB=_oz(z,19,e,s,gg)
_(tSVB,eTVB)
_(oNVB,tSVB)
_(cLVB,oNVB)
var bUVB=_n('view')
_rz(z,bUVB,'class',20,e,s,gg)
var oVVB=_n('view')
_rz(z,oVVB,'class',21,e,s,gg)
var xWVB=_n('text')
_rz(z,xWVB,'class',22,e,s,gg)
var oXVB=_oz(z,23,e,s,gg)
_(xWVB,oXVB)
_(oVVB,xWVB)
var fYVB=_n('text')
_rz(z,fYVB,'class',24,e,s,gg)
var cZVB=_oz(z,25,e,s,gg)
_(fYVB,cZVB)
_(oVVB,fYVB)
_(bUVB,oVVB)
var h1VB=_n('view')
_rz(z,h1VB,'class',26,e,s,gg)
var o2VB=_n('text')
_rz(z,o2VB,'class',27,e,s,gg)
var c3VB=_oz(z,28,e,s,gg)
_(o2VB,c3VB)
_(h1VB,o2VB)
var o4VB=_n('text')
_rz(z,o4VB,'class',29,e,s,gg)
var l5VB=_oz(z,30,e,s,gg)
_(o4VB,l5VB)
_(h1VB,o4VB)
_(bUVB,h1VB)
_(cLVB,bUVB)
var a6VB=_n('view')
_rz(z,a6VB,'class',31,e,s,gg)
var t7VB=_mz(z,'button',['bindtap',32,'class',1,'hoverClass',2,'loading',3],[],e,s,gg)
var e8VB=_oz(z,36,e,s,gg)
_(t7VB,e8VB)
_(a6VB,t7VB)
var b9VB=_mz(z,'button',['bindtap',37,'class',1,'hoverClass',2],[],e,s,gg)
var o0VB=_oz(z,40,e,s,gg)
_(b9VB,o0VB)
_(a6VB,b9VB)
var xAWB=_mz(z,'button',['bindtap',41,'class',1,'hoverClass',2],[],e,s,gg)
var oBWB=_oz(z,44,e,s,gg)
_(xAWB,oBWB)
_(a6VB,xAWB)
_(cLVB,a6VB)
var hMVB=_v()
_(cLVB,hMVB)
if(_oz(z,45,e,s,gg)){hMVB.wxVkey=1
var fCWB=_n('view')
_rz(z,fCWB,'class',46,e,s,gg)
var cDWB=_n('text')
_rz(z,cDWB,'class',47,e,s,gg)
var hEWB=_oz(z,48,e,s,gg)
_(cDWB,hEWB)
_(fCWB,cDWB)
_(hMVB,fCWB)
}
hMVB.wxXCkey=1
_(eFVB,cLVB)
var oFWB=_n('view')
_rz(z,oFWB,'class',49,e,s,gg)
var cGWB=_mz(z,'view',['bindtap',50,'class',1,'data-id',2,'hoverClass',3],[],e,s,gg)
var oHWB=_n('view')
_rz(z,oHWB,'class',54,e,s,gg)
var lIWB=_mz(z,'image',['class',55,'src',1],[],e,s,gg)
_(oHWB,lIWB)
var aJWB=_n('text')
_rz(z,aJWB,'class',57,e,s,gg)
var tKWB=_oz(z,58,e,s,gg)
_(aJWB,tKWB)
_(oHWB,aJWB)
_(cGWB,oHWB)
var eLWB=_n('text')
_rz(z,eLWB,'class',59,e,s,gg)
_(cGWB,eLWB)
_(oFWB,cGWB)
_(eFVB,oFWB)
_(r,eFVB)
var bMWB=_mz(z,'view',['bindtap',60,'class',1],[],e,s,gg)
_(r,bMWB)
var oNWB=_n('view')
_rz(z,oNWB,'class',62,e,s,gg)
var xOWB=_mz(z,'view',['bindtap',63,'class',1],[],e,s,gg)
var oPWB=_n('view')
_rz(z,oPWB,'class',65,e,s,gg)
_(xOWB,oPWB)
_(oNWB,xOWB)
var fQWB=_n('view')
_rz(z,fQWB,'class',66,e,s,gg)
var cRWB=_n('text')
_rz(z,cRWB,'class',67,e,s,gg)
var hSWB=_oz(z,68,e,s,gg)
_(cRWB,hSWB)
_(fQWB,cRWB)
var oTWB=_mz(z,'view',['bindtap',69,'class',1],[],e,s,gg)
var cUWB=_mz(z,'text',['class',71,'style',1],[],e,s,gg)
var oVWB=_oz(z,73,e,s,gg)
_(cUWB,oVWB)
_(oTWB,cUWB)
_(fQWB,oTWB)
_(oNWB,fQWB)
var lWWB=_mz(z,'scroll-view',['scrollY',-1,'class',74],[],e,s,gg)
var aXWB=_v()
_(lWWB,aXWB)
if(_oz(z,75,e,s,gg)){aXWB.wxVkey=1
var b1WB=_n('view')
_rz(z,b1WB,'class',76,e,s,gg)
_(aXWB,b1WB)
}
var tYWB=_v()
_(lWWB,tYWB)
if(_oz(z,77,e,s,gg)){tYWB.wxVkey=1
var o2WB=_n('view')
_rz(z,o2WB,'class',78,e,s,gg)
_(tYWB,o2WB)
}
var eZWB=_v()
_(lWWB,eZWB)
if(_oz(z,79,e,s,gg)){eZWB.wxVkey=1
var x3WB=_n('view')
_rz(z,x3WB,'class',80,e,s,gg)
var o4WB=_n('view')
_rz(z,o4WB,'class',81,e,s,gg)
var f5WB=_n('view')
_rz(z,f5WB,'class',82,e,s,gg)
var c6WB=_oz(z,83,e,s,gg)
_(f5WB,c6WB)
_(o4WB,f5WB)
var h7WB=_n('view')
_rz(z,h7WB,'class',84,e,s,gg)
var o8WB=_oz(z,85,e,s,gg)
_(h7WB,o8WB)
var c9WB=_n('text')
_rz(z,c9WB,'class',86,e,s,gg)
var o0WB=_oz(z,87,e,s,gg)
_(c9WB,o0WB)
_(h7WB,c9WB)
var lAXB=_oz(z,88,e,s,gg)
_(h7WB,lAXB)
_(o4WB,h7WB)
_(x3WB,o4WB)
var aBXB=_n('view')
_rz(z,aBXB,'class',89,e,s,gg)
var tCXB=_n('view')
_rz(z,tCXB,'class',90,e,s,gg)
var eDXB=_oz(z,91,e,s,gg)
_(tCXB,eDXB)
_(aBXB,tCXB)
var bEXB=_n('view')
_rz(z,bEXB,'class',92,e,s,gg)
var oFXB=_mz(z,'text',['class',93,'style',1],[],e,s,gg)
var xGXB=_oz(z,95,e,s,gg)
_(oFXB,xGXB)
_(bEXB,oFXB)
var oHXB=_n('view')
_rz(z,oHXB,'class',96,e,s,gg)
var fIXB=_oz(z,97,e,s,gg)
_(oHXB,fIXB)
_(bEXB,oHXB)
_(aBXB,bEXB)
var cJXB=_n('view')
_rz(z,cJXB,'class',98,e,s,gg)
var hKXB=_mz(z,'view',['class',99,'style',1],[],e,s,gg)
var oLXB=_oz(z,101,e,s,gg)
_(hKXB,oLXB)
_(cJXB,hKXB)
var cMXB=_n('view')
_rz(z,cMXB,'class',102,e,s,gg)
var oNXB=_oz(z,103,e,s,gg)
_(cMXB,oNXB)
_(cJXB,cMXB)
var lOXB=_n('view')
var aPXB=_oz(z,104,e,s,gg)
_(lOXB,aPXB)
var tQXB=_n('text')
_rz(z,tQXB,'class',105,e,s,gg)
var eRXB=_oz(z,106,e,s,gg)
_(tQXB,eRXB)
_(lOXB,tQXB)
var bSXB=_oz(z,107,e,s,gg)
_(lOXB,bSXB)
_(cJXB,lOXB)
_(aBXB,cJXB)
var oTXB=_n('view')
_rz(z,oTXB,'class',108,e,s,gg)
var xUXB=_mz(z,'view',['class',109,'style',1],[],e,s,gg)
var oVXB=_oz(z,111,e,s,gg)
_(xUXB,oVXB)
_(oTXB,xUXB)
var fWXB=_n('view')
_rz(z,fWXB,'class',112,e,s,gg)
var cXXB=_oz(z,113,e,s,gg)
_(fWXB,cXXB)
_(oTXB,fWXB)
var hYXB=_n('view')
var oZXB=_oz(z,114,e,s,gg)
_(hYXB,oZXB)
var c1XB=_n('text')
_rz(z,c1XB,'class',115,e,s,gg)
var o2XB=_oz(z,116,e,s,gg)
_(c1XB,o2XB)
_(hYXB,c1XB)
var l3XB=_oz(z,117,e,s,gg)
_(hYXB,l3XB)
_(oTXB,hYXB)
var a4XB=_n('view')
_rz(z,a4XB,'class',118,e,s,gg)
var t5XB=_oz(z,119,e,s,gg)
_(a4XB,t5XB)
var e6XB=_n('text')
_rz(z,e6XB,'class',120,e,s,gg)
var b7XB=_oz(z,121,e,s,gg)
_(e6XB,b7XB)
_(a4XB,e6XB)
var o8XB=_oz(z,122,e,s,gg)
_(a4XB,o8XB)
_(oTXB,a4XB)
_(aBXB,oTXB)
var x9XB=_n('view')
_rz(z,x9XB,'class',123,e,s,gg)
var o0XB=_mz(z,'view',['class',124,'style',1],[],e,s,gg)
var fAYB=_oz(z,126,e,s,gg)
_(o0XB,fAYB)
_(x9XB,o0XB)
var cBYB=_n('view')
_rz(z,cBYB,'class',127,e,s,gg)
var hCYB=_oz(z,128,e,s,gg)
_(cBYB,hCYB)
_(x9XB,cBYB)
var oDYB=_n('view')
var cEYB=_oz(z,129,e,s,gg)
_(oDYB,cEYB)
var oFYB=_n('text')
_rz(z,oFYB,'class',130,e,s,gg)
var lGYB=_oz(z,131,e,s,gg)
_(oFYB,lGYB)
_(oDYB,oFYB)
var aHYB=_oz(z,132,e,s,gg)
_(oDYB,aHYB)
_(x9XB,oDYB)
_(aBXB,x9XB)
_(x3WB,aBXB)
_(eZWB,x3WB)
}
var tIYB=_n('view')
_rz(z,tIYB,'style',133,e,s,gg)
_(lWWB,tIYB)
aXWB.wxXCkey=1
tYWB.wxXCkey=1
eZWB.wxXCkey=1
_(oNWB,lWWB)
_(r,oNWB)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_82";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_82();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/FAQ/index.wxml'] = [$gwx_XC_82, './pages/FAQ/index.wxml'];else __wxAppCode__['pages/FAQ/index.wxml'] = $gwx_XC_82( './pages/FAQ/index.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/FAQ/index.wxss']=setCssToHead(["body{background-color:#f2f2f7;font-family:-apple-system,BlinkMacSystemFont,Helvetica Neue,Helvetica,Segoe UI,Arial,Roboto,PingFang SC,sans-serif}\n.",[1],"background-blobs{background:#f5f7fa;height:100vh;left:0;pointer-events:none;position:fixed;top:0;width:100%;z-index:-1}\n.",[1],"blob{border-radius:50%;-webkit-filter:blur(60px);filter:blur(60px);opacity:.6;position:absolute}\n.",[1],"blob-1{-webkit-animation:float 10s ease-in-out infinite;animation:float 10s ease-in-out infinite;background:#a0c4ff;height:",[0,400],";right:",[0,-50],";top:",[0,-100],";width:",[0,400],"}\n.",[1],"blob-2{animation:float 8s ease-in-out infinite reverse;background:#ffccbc;bottom:20%;height:",[0,350],";left:",[0,-50],";width:",[0,350],"}\n@-webkit-keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}@keyframes float{0%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n50%{-webkit-transform:translate(20px,30px);transform:translate(20px,30px)}\n100%{-webkit-transform:translate(0,0);transform:translate(0,0)}\n}.",[1],"main-container{padding:",[0,40],"}\n.",[1],"nav-placeholder{height:",[0,20],"}\n.",[1],"header-section{margin-bottom:",[0,40],"}\n.",[1],"block{display:block}\n.",[1],"glass-group{backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);background:hsla(0,0%,100%,.75);border:1px solid hsla(0,0%,100%,.5);border-radius:",[0,24],";box-shadow:0 ",[0,4]," ",[0,16]," rgba(0,0,0,.03);overflow:hidden}\n.",[1],"ios-cell{-webkit-align-items:center;align-items:center;background:transparent;border-bottom:",[0,1]," solid rgba(0,0,0,.05);display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,32],";transition:background .2s}\n.",[1],"ios-cell:last-child{border-bottom:none}\n.",[1],"cell-hover{background-color:rgba(0,0,0,.03)}\n.",[1],"cell-icon{height:",[0,44],";margin-right:",[0,20],";opacity:.8;width:",[0,44],"}\n.",[1],"cell-text{color:#1c1c1e;font-size:",[0,30],";font-weight:500}\n.",[1],"cuIcon-right{color:#c7c7cc;font-size:",[0,28],"}\n.",[1],"glass-sheet-mask{background:rgba(0,0,0,.3);height:100%;left:0;opacity:0;position:fixed;top:0;transition:all .3s;visibility:hidden;width:100%;z-index:999}\n.",[1],"glass-sheet-mask.",[1],"show{opacity:1;visibility:visible}\n.",[1],"glass-sheet{backdrop-filter:blur(25px);-webkit-backdrop-filter:blur(25px);background:hsla(0,0%,100%,.9);border-radius:",[0,32]," ",[0,32]," 0 0;bottom:0;box-shadow:0 ",[0,-10]," ",[0,40]," rgba(0,0,0,.1);display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;height:85vh;left:0;position:fixed;-webkit-transform:translateY(100%);transform:translateY(100%);transition:-webkit-transform .35s cubic-bezier(.19,1,.22,1);transition:transform .35s cubic-bezier(.19,1,.22,1);transition:transform .35s cubic-bezier(.19,1,.22,1),-webkit-transform .35s cubic-bezier(.19,1,.22,1);width:100%;z-index:1000}\n.",[1],"glass-sheet.",[1],"show{-webkit-transform:translateY(0);transform:translateY(0)}\n.",[1],"drag-handle-bar{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0;height:",[0,40],";-webkit-justify-content:center;justify-content:center}\n.",[1],"drag-handle{background:#e5e5ea;border-radius:",[0,10],";height:",[0,10],";width:",[0,80],"}\n.",[1],"sheet-header{-webkit-flex-shrink:0;flex-shrink:0;-webkit-justify-content:space-between;justify-content:space-between;padding:",[0,10]," ",[0,40]," ",[0,30],"}\n.",[1],"close-btn,.",[1],"sheet-header{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"close-btn{background:rgba(0,0,0,.05);border-radius:50%;height:",[0,60],";-webkit-justify-content:center;justify-content:center;width:",[0,60],"}\n.",[1],"sheet-content{box-sizing:border-box;-webkit-flex:1;flex:1;padding:0 ",[0,40],"}\n.",[1],"article-box{padding-top:",[0,10],"}\n.",[1],"qa-item{margin-bottom:",[0,50],"}\n.",[1],"q-title{color:#1c1c1e;font-size:",[0,32],";font-weight:700;line-height:1.4;margin-bottom:",[0,16],"}\n.",[1],"a-text{color:#48484a;font-size:",[0,28],";line-height:1.6;margin-bottom:",[0,10],"}\n.",[1],"notice-box{background:rgba(255,59,48,.08);border-radius:",[0,16],";padding:",[0,20],"}\n.",[1],"text-red{font-size:",[0,26],"}\n.",[1],"img-group{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;gap:",[0,20],";margin-top:",[0,20],"}\n.",[1],"faq-img{border-radius:",[0,16],";display:block;width:100%}\n.",[1],"shadow-sm{box-shadow:0 ",[0,4]," ",[0,12]," rgba(0,0,0,.08)}\n.",[1],"text-xxl{font-size:",[0,48],"}\n.",[1],"text-xl{font-size:",[0,36],"}\n.",[1],"text-bold{font-weight:700}\n.",[1],"text-sm{font-size:",[0,26],"}\n.",[1],"text-gray{color:#8e8e93}\n.",[1],"text-black{color:#1c1c1e}\n.",[1],"margin-top-lg{margin-top:",[0,60],"}\n.",[1],"margin-top-sm{margin-top:",[0,16],"}\n.",[1],"margin-top{margin-top:",[0,30],"}\n.",[1],"flex{display:-webkit-flex;display:flex}\n.",[1],"align-center{-webkit-align-items:center;align-items:center}\n.",[1],"fade-in{-webkit-animation:fadeIn .6s ease-out forwards;animation:fadeIn .6s ease-out forwards;opacity:0;-webkit-transform:translateY(",[0,20],");transform:translateY(",[0,20],")}\n@-webkit-keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"diagnostic-card{backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);background:hsla(0,0%,100%,.85);border:1px solid hsla(0,0%,100%,.6);border-radius:",[0,28],";box-shadow:0 ",[0,8]," ",[0,24]," rgba(0,0,0,.04);margin-bottom:",[0,30],";padding:",[0,30],"}\n.",[1],"card-header{margin-bottom:",[0,20],"}\n.",[1],"card-icon{height:",[0,44],";margin-right:",[0,12],";width:",[0,44],"}\n.",[1],"justify-between{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"status-badge{border-radius:",[0,40],";font-size:",[0,24],";font-weight:500;padding:",[0,6]," ",[0,20],"}\n.",[1],"status-ok{background-color:rgba(52,199,89,.15);color:#34c759}\n.",[1],"status-warn{background-color:rgba(255,149,0,.15);color:#ff9500}\n.",[1],"status-row{background:rgba(0,0,0,.02);border-radius:",[0,16],";margin-bottom:",[0,24],";padding:",[0,16]," 0}\n.",[1],"status-item,.",[1],"status-row{display:-webkit-flex;display:flex}\n.",[1],"status-item{-webkit-align-items:center;align-items:center;-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"status-label{color:#8e8e93;font-size:",[0,24],";margin-bottom:",[0,8],"}\n.",[1],"status-value{font-size:",[0,30],";font-weight:600}\n.",[1],"text-green{color:#34c759}\n.",[1],"text-red{color:#ff3b30}\n.",[1],"action-buttons{gap:",[0,16],";margin-top:",[0,10],"}\n.",[1],"diagnostic-btn{background:transparent;border:none;border-radius:",[0,36],";-webkit-flex:1;flex:1;font-size:",[0,28],";height:",[0,72],";line-height:",[0,72],";margin:0;padding:0;text-align:center}\n.",[1],"diagnostic-btn.",[1],"primary{background:#007aff;box-shadow:0 ",[0,4]," ",[0,12]," rgba(0,122,255,.3);color:#fff}\n.",[1],"diagnostic-btn.",[1],"secondary{background:hsla(240,3%,49%,.1);border:.5px solid rgba(0,0,0,.05);color:#1c1c1e}\n.",[1],"btn-hover{opacity:.7}\n.",[1],"last-check{margin-top:",[0,20],";text-align:right}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/FAQ/index.wxss:1:1)",{path:"./pages/FAQ/index.wxss"});
}