$gwx_XC_92=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_92 || [];
function gz$gwx_XC_92_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_92_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_92_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_92_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'background-blobs'])
Z([3,'blob blob-1'])
Z([3,'blob blob-2'])
Z([3,'nav-placeholder'])
Z([3,'main-container fade-in'])
Z([3,'glass-card flex justify-between align-center padding-sm margin-bottom'])
Z([3,'flex align-center'])
Z([3,'type-icon'])
Z([[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,2]],[1,'https://img.icons8.com/ios-filled/50/34c759/running.png'],[1,'https://img.icons8.com/ios-filled/50/ff9500/sun.png']])
Z([3,'flex flex-direction margin-left-sm'])
Z([3,'text-lg text-bold'])
Z([a,[[2,'?:'],[[2,'=='],[[7],[3,'runType']],[1,2]],[1,'自由跑'],[1,'阳光跑']]])
Z([3,'text-xs text-gray'])
Z([3,'查看详细数据'])
Z([3,'copyEncryptedText'])
Z([3,'action-btn'])
Z([3,'mini-icon'])
Z([3,'https://img.icons8.com/ios/50/007aff/copy.png'])
Z([3,'text-blue text-sm'])
Z([3,'复制'])
Z([3,'user-pill-glass flex align-center margin-bottom'])
Z([3,'text-bold text-black margin-left-xs'])
Z([3,'font-size:28rpx;'])
Z([a,[[6],[[7],[3,'userInfo']],[3,'studentName']]])
Z([3,'text-gray margin-left-xs'])
Z([3,'font-size:24rpx;'])
Z([a,[[6],[[7],[3,'userInfo']],[3,'schoolCampusName']]])
Z([3,'text-gray margin-left-sm din-font'])
Z(z[25])
Z([a,[[6],[[7],[3,'userInfo']],[3,'snCode']]])
Z([3,'glass-card padding-lg margin-bottom text-center'])
Z([3,'margin-bottom-lg'])
Z([3,'flex align-baseline justify-center'])
Z([3,'hero-number din-font'])
Z([a,[[7],[3,'distance_data']]])
Z([3,'text-gray text-xl margin-left-xs'])
Z([3,'km'])
Z([3,'text-gray text-sm'])
Z([3,'总里程'])
Z([3,'grid-info'])
Z([3,'grid-item'])
Z([3,'sub-number din-font'])
Z([a,[[7],[3,'time_data']]])
Z([3,'sub-label'])
Z([3,'时长'])
Z([3,'grid-item border-left border-right'])
Z(z[41])
Z([a,[[7],[3,'speed_data']]])
Z(z[43])
Z([3,'平均配速'])
Z(z[40])
Z(z[41])
Z([a,[[7],[3,'kcal_data']]])
Z(z[43])
Z([3,'千卡'])
Z([3,'margin-top-sm pt-sm border-top flex justify-center align-center'])
Z(z[12])
Z([3,'轨迹拟合度'])
Z([3,'text-sm text-black margin-left-xs text-bold'])
Z([a,[[7],[3,'fitDegree']]])
Z([[7],[3,'runPointData']])
Z([3,'glass-card padding margin-bottom'])
Z([3,'flex justify-between align-center'])
Z([3,'section-title'])
Z([3,'打卡状态'])
Z([a,[3,'status-badge '],[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,1]],[1,'bg-green'],[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,2]],[1,'bg-blue'],[1,'bg-red']]]])
Z([a,[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,0]],[1,'请补卡'],[[2,'?:'],[[2,'=='],[[6],[[7],[3,'runPointData']],[3,'runPointType']],[1,1]],[1,'无需补卡'],[1,'已补卡']]]])
Z([3,'glass-card  margin-bottom'])
Z([3,'overflow:hidden;'])
Z([[2,'||'],[[2,'=='],[[7],[3,'runType']],[1,0]],[[2,'=='],[[7],[3,'runType']],[1,2]]])
Z([3,'myMap'])
Z([[7],[3,'latitude']])
Z([[7],[3,'longitude']])
Z([[7],[3,'polyline']])
Z([1,16])
Z([3,'width:100%;height:500rpx;border-radius:24rpx;'])
Z(z[61])
Z([3,'flex align-center margin-bottom'])
Z([3,'chart-icon'])
Z([3,'https://img.icons8.com/ios-filled/50/ff9500/speed.png'])
Z(z[63])
Z([3,'配速分析'])
Z([3,'touchEndLineA'])
Z([3,'moveLineA'])
Z([3,'touchLineA'])
Z([3,'canvasLineA'])
Z([3,'charts'])
Z(z[85])
Z(z[61])
Z(z[77])
Z(z[78])
Z([3,'https://img.icons8.com/ios-filled/50/007aff/mountain.png'])
Z(z[63])
Z([3,'海拔趋势'])
Z([3,'touchEndLineB'])
Z([3,'moveLineB'])
Z([3,'touchLineB'])
Z([3,'canvasLineB'])
Z(z[86])
Z(z[97])
Z([3,'padding-bottom-xl margin-top-lg flex'])
Z([3,'toShare'])
Z([3,'ios-btn bg-blue margin-bottom'])
Z([3,'生成分享海报'])
Z([3,'delHistory'])
Z([3,'ios-btn bg-white margin-bottom text-red border-red'])
Z([3,'删除此记录'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_92_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_92_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_92=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_92=true;
var x=['./pages/history/detail.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_92_1()
var oN5B=_n('view')
_rz(z,oN5B,'class',0,e,s,gg)
var lO5B=_n('view')
_rz(z,lO5B,'class',1,e,s,gg)
_(oN5B,lO5B)
var aP5B=_n('view')
_rz(z,aP5B,'class',2,e,s,gg)
_(oN5B,aP5B)
_(r,oN5B)
var tQ5B=_n('view')
_rz(z,tQ5B,'class',3,e,s,gg)
_(r,tQ5B)
var eR5B=_n('view')
_rz(z,eR5B,'class',4,e,s,gg)
var oT5B=_n('view')
_rz(z,oT5B,'class',5,e,s,gg)
var xU5B=_n('view')
_rz(z,xU5B,'class',6,e,s,gg)
var oV5B=_mz(z,'image',['class',7,'src',1],[],e,s,gg)
_(xU5B,oV5B)
var fW5B=_n('view')
_rz(z,fW5B,'class',9,e,s,gg)
var cX5B=_n('text')
_rz(z,cX5B,'class',10,e,s,gg)
var hY5B=_oz(z,11,e,s,gg)
_(cX5B,hY5B)
_(fW5B,cX5B)
var oZ5B=_n('text')
_rz(z,oZ5B,'class',12,e,s,gg)
var c15B=_oz(z,13,e,s,gg)
_(oZ5B,c15B)
_(fW5B,oZ5B)
_(xU5B,fW5B)
_(oT5B,xU5B)
var o25B=_mz(z,'view',['bindtap',14,'class',1],[],e,s,gg)
var l35B=_mz(z,'image',['class',16,'src',1],[],e,s,gg)
_(o25B,l35B)
var a45B=_n('text')
_rz(z,a45B,'class',18,e,s,gg)
var t55B=_oz(z,19,e,s,gg)
_(a45B,t55B)
_(o25B,a45B)
_(oT5B,o25B)
_(eR5B,oT5B)
var e65B=_n('view')
_rz(z,e65B,'class',20,e,s,gg)
var b75B=_mz(z,'view',['class',21,'style',1],[],e,s,gg)
var o85B=_oz(z,23,e,s,gg)
_(b75B,o85B)
_(e65B,b75B)
var x95B=_mz(z,'view',['class',24,'style',1],[],e,s,gg)
var o05B=_oz(z,26,e,s,gg)
_(x95B,o05B)
_(e65B,x95B)
var fA6B=_mz(z,'view',['class',27,'style',1],[],e,s,gg)
var cB6B=_oz(z,29,e,s,gg)
_(fA6B,cB6B)
_(e65B,fA6B)
_(eR5B,e65B)
var hC6B=_n('view')
_rz(z,hC6B,'class',30,e,s,gg)
var oD6B=_n('view')
_rz(z,oD6B,'class',31,e,s,gg)
var cE6B=_n('view')
_rz(z,cE6B,'class',32,e,s,gg)
var oF6B=_n('text')
_rz(z,oF6B,'class',33,e,s,gg)
var lG6B=_oz(z,34,e,s,gg)
_(oF6B,lG6B)
_(cE6B,oF6B)
var aH6B=_n('text')
_rz(z,aH6B,'class',35,e,s,gg)
var tI6B=_oz(z,36,e,s,gg)
_(aH6B,tI6B)
_(cE6B,aH6B)
_(oD6B,cE6B)
var eJ6B=_n('text')
_rz(z,eJ6B,'class',37,e,s,gg)
var bK6B=_oz(z,38,e,s,gg)
_(eJ6B,bK6B)
_(oD6B,eJ6B)
_(hC6B,oD6B)
var oL6B=_n('view')
_rz(z,oL6B,'class',39,e,s,gg)
var xM6B=_n('view')
_rz(z,xM6B,'class',40,e,s,gg)
var oN6B=_n('text')
_rz(z,oN6B,'class',41,e,s,gg)
var fO6B=_oz(z,42,e,s,gg)
_(oN6B,fO6B)
_(xM6B,oN6B)
var cP6B=_n('text')
_rz(z,cP6B,'class',43,e,s,gg)
var hQ6B=_oz(z,44,e,s,gg)
_(cP6B,hQ6B)
_(xM6B,cP6B)
_(oL6B,xM6B)
var oR6B=_n('view')
_rz(z,oR6B,'class',45,e,s,gg)
var cS6B=_n('text')
_rz(z,cS6B,'class',46,e,s,gg)
var oT6B=_oz(z,47,e,s,gg)
_(cS6B,oT6B)
_(oR6B,cS6B)
var lU6B=_n('text')
_rz(z,lU6B,'class',48,e,s,gg)
var aV6B=_oz(z,49,e,s,gg)
_(lU6B,aV6B)
_(oR6B,lU6B)
_(oL6B,oR6B)
var tW6B=_n('view')
_rz(z,tW6B,'class',50,e,s,gg)
var eX6B=_n('text')
_rz(z,eX6B,'class',51,e,s,gg)
var bY6B=_oz(z,52,e,s,gg)
_(eX6B,bY6B)
_(tW6B,eX6B)
var oZ6B=_n('text')
_rz(z,oZ6B,'class',53,e,s,gg)
var x16B=_oz(z,54,e,s,gg)
_(oZ6B,x16B)
_(tW6B,oZ6B)
_(oL6B,tW6B)
_(hC6B,oL6B)
var o26B=_n('view')
_rz(z,o26B,'class',55,e,s,gg)
var f36B=_n('text')
_rz(z,f36B,'class',56,e,s,gg)
var c46B=_oz(z,57,e,s,gg)
_(f36B,c46B)
_(o26B,f36B)
var h56B=_n('text')
_rz(z,h56B,'class',58,e,s,gg)
var o66B=_oz(z,59,e,s,gg)
_(h56B,o66B)
_(o26B,h56B)
_(hC6B,o26B)
_(eR5B,hC6B)
var bS5B=_v()
_(eR5B,bS5B)
if(_oz(z,60,e,s,gg)){bS5B.wxVkey=1
var c76B=_n('view')
_rz(z,c76B,'class',61,e,s,gg)
var o86B=_n('view')
_rz(z,o86B,'class',62,e,s,gg)
var l96B=_n('text')
_rz(z,l96B,'class',63,e,s,gg)
var a06B=_oz(z,64,e,s,gg)
_(l96B,a06B)
_(o86B,l96B)
var tA7B=_n('view')
_rz(z,tA7B,'class',65,e,s,gg)
var eB7B=_oz(z,66,e,s,gg)
_(tA7B,eB7B)
_(o86B,tA7B)
_(c76B,o86B)
_(bS5B,c76B)
}
var bC7B=_mz(z,'view',['class',67,'style',1],[],e,s,gg)
var oD7B=_v()
_(bC7B,oD7B)
if(_oz(z,69,e,s,gg)){oD7B.wxVkey=1
var xE7B=_mz(z,'map',['showLocation',-1,'id',70,'latitude',1,'longitude',2,'polyline',3,'scale',4,'style',5],[],e,s,gg)
_(oD7B,xE7B)
}
oD7B.wxXCkey=1
_(eR5B,bC7B)
var oF7B=_n('view')
_rz(z,oF7B,'class',76,e,s,gg)
var fG7B=_n('view')
_rz(z,fG7B,'class',77,e,s,gg)
var cH7B=_mz(z,'image',['class',78,'src',1],[],e,s,gg)
_(fG7B,cH7B)
var hI7B=_n('text')
_rz(z,hI7B,'class',80,e,s,gg)
var oJ7B=_oz(z,81,e,s,gg)
_(hI7B,oJ7B)
_(fG7B,hI7B)
_(oF7B,fG7B)
var cK7B=_mz(z,'canvas',['bindtouchend',82,'bindtouchmove',1,'bindtouchstart',2,'canvasId',3,'class',4,'id',5],[],e,s,gg)
_(oF7B,cK7B)
_(eR5B,oF7B)
var oL7B=_n('view')
_rz(z,oL7B,'class',88,e,s,gg)
var lM7B=_n('view')
_rz(z,lM7B,'class',89,e,s,gg)
var aN7B=_mz(z,'image',['class',90,'src',1],[],e,s,gg)
_(lM7B,aN7B)
var tO7B=_n('text')
_rz(z,tO7B,'class',92,e,s,gg)
var eP7B=_oz(z,93,e,s,gg)
_(tO7B,eP7B)
_(lM7B,tO7B)
_(oL7B,lM7B)
var bQ7B=_mz(z,'canvas',['bindtouchend',94,'bindtouchmove',1,'bindtouchstart',2,'canvasId',3,'class',4,'id',5],[],e,s,gg)
_(oL7B,bQ7B)
_(eR5B,oL7B)
var oR7B=_n('view')
_rz(z,oR7B,'class',100,e,s,gg)
var xS7B=_mz(z,'button',['bindtap',101,'class',1],[],e,s,gg)
var oT7B=_oz(z,103,e,s,gg)
_(xS7B,oT7B)
_(oR7B,xS7B)
var fU7B=_mz(z,'button',['bindtap',104,'class',1],[],e,s,gg)
var cV7B=_oz(z,106,e,s,gg)
_(fU7B,cV7B)
_(oR7B,fU7B)
_(eR5B,oR7B)
bS5B.wxXCkey=1
_(r,eR5B)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_92";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_92();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/history/detail.wxml'] = [$gwx_XC_92, './pages/history/detail.wxml'];else __wxAppCode__['pages/history/detail.wxml'] = $gwx_XC_92( './pages/history/detail.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/history/detail.wxss']=setCssToHead(["body{background-color:#f2f2f7;font-family:-apple-system,BlinkMacSystemFont,Helvetica Neue,Helvetica,Segoe UI,Arial,Roboto,PingFang SC,sans-serif}\n.",[1],"background-blobs{height:100vh;left:0;pointer-events:none;position:fixed;top:0;width:100%;z-index:0}\n.",[1],"blob{border-radius:50%;-webkit-filter:blur(60px);filter:blur(60px);opacity:.6;position:absolute}\n.",[1],"blob-1{-webkit-animation:float 8s ease-in-out infinite;animation:float 8s ease-in-out infinite;background:#a0c4ff;height:300px;left:-50px;top:-50px;width:300px}\n.",[1],"blob-2{animation:float 8s ease-in-out infinite reverse;background:#b9fbc0;bottom:-50px;height:250px;right:-50px;width:250px}\n.",[1],"main-container{padding:",[0,30],"}\n.",[1],"nav-placeholder{height:",[0,20],"}\n.",[1],"glass-card{backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);background:hsla(0,0%,100%,.15);border:1px solid hsla(0,0%,100%,.8);border-radius:",[0,32],";box-shadow:0 8px 32px 0 rgba(31,38,135,.15);overflow:hidden}\n.",[1],"type-icon{height:",[0,60],";width:",[0,60],"}\n.",[1],"action-btn{-webkit-align-items:center;align-items:center;background:rgba(0,122,255,.1);border-radius:",[0,100],";display:-webkit-flex;display:flex;padding:",[0,10]," ",[0,20],"}\n.",[1],"mini-icon{height:",[0,30],";margin-right:",[0,8],";width:",[0,30],"}\n@font-face{font-family:DINPro-Regular;src:url(\x22https://cppu.xtotoro.com/longmao/sunrunwx/font/DINPro-Regular.otf\x22)}\n.",[1],"din-font{font-family:DINPro-Regular,-apple-system,sans-serif}\n.",[1],"hero-number{color:#1c1c1e;font-size:",[0,100],";font-weight:700;line-height:1}\n.",[1],"grid-info{-webkit-justify-content:space-around;justify-content:space-around}\n.",[1],"grid-info,.",[1],"grid-item{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"grid-item{-webkit-flex:1;flex:1;-webkit-flex-direction:column;flex-direction:column}\n.",[1],"sub-number{color:#1c1c1e;font-size:",[0,44],";font-weight:600}\n.",[1],"sub-label{color:#8e8e93;font-size:",[0,24],";margin-top:",[0,6],"}\n.",[1],"border-left{border-left:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"border-right{border-right:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"border-top{border-top:",[0,1]," solid rgba(0,0,0,.06)}\n.",[1],"status-badge{border-radius:",[0,8],";color:#fff;font-size:",[0,22],";padding:",[0,6]," ",[0,16],"}\n.",[1],"bg-green{background:#34c759}\n.",[1],"bg-red{background:#ff3b30}\n.",[1],"section-title{color:#1c1c1e;font-size:",[0,30],";font-weight:600}\n.",[1],"chart-icon{height:",[0,36],";margin-right:",[0,12],";width:",[0,36],"}\n.",[1],"charts{background-color:initial;height:",[0,400],";width:100%}\n.",[1],"ios-btn{border-radius:",[0,24],";box-shadow:0 ",[0,4]," ",[0,12]," rgba(0,0,0,.05);font-size:",[0,32],";font-weight:600;width:40%}\n.",[1],"ios-btn::after{border:none}\n.",[1],"bg-blue{background:#007aff;color:#fff}\n.",[1],"bg-white{-webkit-backdrop-filter:blur(10px);backdrop-filter:blur(10px);background:hsla(0,0%,100%,.8)}\n.",[1],"border-red{border:",[0,1]," solid rgba(255,59,48,.3)}\n.",[1],"flex{display:-webkit-flex;display:flex}\n.",[1],"flex-direction{-webkit-flex-direction:column;flex-direction:column}\n.",[1],"justify-between{-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"justify-center{-webkit-justify-content:center;justify-content:center}\n.",[1],"align-center{-webkit-align-items:center;align-items:center}\n.",[1],"align-baseline{-webkit-align-items:baseline;align-items:baseline}\n.",[1],"flex-sub{-webkit-flex:1;flex:1}\n.",[1],"text-center{text-align:center}\n.",[1],"margin-bottom{margin-bottom:",[0,30],"}\n.",[1],"margin-bottom-lg{margin-bottom:",[0,50],"}\n.",[1],"margin-bottom-sm{margin-bottom:",[0,20],"}\n.",[1],"margin-top-lg{margin-top:",[0,60],"}\n.",[1],"margin-top-sm{margin-top:",[0,20],"}\n.",[1],"padding{padding:",[0,30],"}\n.",[1],"padding-lg{padding:",[0,40],"}\n.",[1],"padding-sm{padding:",[0,20],"}\n.",[1],"padding-xs{padding:",[0,10],"}\n.",[1],"pt-sm{padding-top:",[0,20],"}\n.",[1],"padding-bottom-xl{padding-bottom:",[0,60],"}\n.",[1],"margin-left-sm{margin-left:",[0,20],"}\n.",[1],"margin-left-xs{margin-left:",[0,10],"}\n.",[1],"text-bold{font-weight:600}\n.",[1],"text-lg{font-size:",[0,34],"}\n.",[1],"text-xl{font-size:",[0,38],"}\n.",[1],"text-sm{font-size:",[0,26],"}\n.",[1],"text-xs{font-size:",[0,22],"}\n.",[1],"text-gray{color:#8e8e93}\n.",[1],"text-blue{color:#007aff}\n.",[1],"text-red{color:#ff3b30}\n.",[1],"text-green{color:#34c759}\n.",[1],"fade-in{-webkit-animation:fadeIn .6s ease-out forwards;animation:fadeIn .6s ease-out forwards;opacity:0;-webkit-transform:translateY(",[0,20],");transform:translateY(",[0,20],")}\n@-webkit-keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}@keyframes fadeIn{to{opacity:1;-webkit-transform:translateY(0);transform:translateY(0)}\n}.",[1],"user-pill-glass{backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);background:hsla(0,0%,100%,.15);border:",[0,1]," solid hsla(0,0%,100%,.4);border-radius:",[0,32],";box-sizing:border-box;height:24px;padding:",[0,6]," ",[0,14],"}\n.",[1],"border-top-white-light{background-color:hsla(0,0%,100%,.2);height:1px;width:100%}\n.",[1],"bg-white-transparent{background-color:hsla(0,0%,100%,.15)}\n.",[1],"border-top-dashed{border-top:1px dashed hsla(0,0%,100%,.3)}\n.",[1],"text-xxl{font-size:",[0,44],"}\n.",[1],"text-md{font-size:",[0,28],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/history/detail.wxss:1:1)",{path:"./pages/history/detail.wxss"});
}